% ========================================================================
% Copyright (C) 2023 / 2024, Advanced Micro Devices, Inc. All rights reserved.
% SPDX-License-Identifier: MIT
%
% Author: Bachir Berkane, Fidus Systems

% Script to test Music Algorithm and generate test Vector for AIE sims.
% This script runs only 1 test with signal as generated by the system 
% model SystemModel/systemModel.m configured as defined in Configuration/testCfg

%% Configutaion and Misc
clear; %clc;
restoredefaultpath
addpath Commun Configuration SystemModel GSSR  NoiseSS LogPlotScripts DOA


%% Get the configuration parameters : Model and Music algorithm
cfg = testCfg(); 
fprintf('\n<strong>- Note:</strong> Number of Sources set to %d, the length of the specified DOA vector\n ', cfg.nSource);
 
%% Run system model to generate snapshot matrix
[A, cfg]  = systemModel(cfg);



%% Apply Music Algorithm 
data = music(A, cfg);

% Plot results
if ( cfg.visiblePlot == "on")
    plotMusicResults (data, cfg);
end

%% Log Golden Data ...  If instructed
if (cfg.log == "on")
    saveMusicData(data, cfg);
end

restoredefaultpath;
