#!/usr/bin/env python3
# Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: X11
#

import os
import subprocess
import sys

from ProcessAIEOutputLib import *

# gets variable from parameters
NArgs = len(sys.argv)-1
Args = sys.argv
Args[0] = 'ls'

if (NArgs<1): # No argument !!
  exit

Args1 = subprocess.check_output(' '.join(Args),shell=True,text=True)
Args1 = Args1.split()
NArgs = len(Args1)

print(Args1)

if(NArgs>=1):
    ComputeThroughput(Args1)
