/*Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
SPDX-License-Identifier: MIT
*/

#include "nbody_subsystem.h"

#define NUM_INSTANCES 100

using namespace adf;


template <int COL_OFFSET>
class nbodySystem : public adf::graph {
	
public:
	input_port in_i[NUM_INSTANCES];
	input_port in_j; 	
	output_port out[NUM_INSTANCES];
        
            //COL 0-49, ROW 0
            nbodySubsystem<COL_OFFSET+0, 0>  nbody_inst0;
            nbodySubsystem<COL_OFFSET+1, 0>  nbody_inst1;
            nbodySubsystem<COL_OFFSET+2, 0>  nbody_inst2;
            nbodySubsystem<COL_OFFSET+3, 0>  nbody_inst3;
            nbodySubsystem<COL_OFFSET+4, 0>  nbody_inst4;
            nbodySubsystem<COL_OFFSET+5, 0>  nbody_inst5;
            nbodySubsystem<COL_OFFSET+6, 0>  nbody_inst6;
            nbodySubsystem<COL_OFFSET+7, 0>  nbody_inst7;
            nbodySubsystem<COL_OFFSET+8, 0>  nbody_inst8;
            nbodySubsystem<COL_OFFSET+9, 0>  nbody_inst9;
            nbodySubsystem<COL_OFFSET+10, 0>  nbody_inst10;
            nbodySubsystem<COL_OFFSET+11, 0>  nbody_inst11;
            nbodySubsystem<COL_OFFSET+12, 0>  nbody_inst12;
            nbodySubsystem<COL_OFFSET+13, 0>  nbody_inst13;
            nbodySubsystem<COL_OFFSET+14, 0>  nbody_inst14;
            nbodySubsystem<COL_OFFSET+15, 0>  nbody_inst15;
            nbodySubsystem<COL_OFFSET+16, 0>  nbody_inst16;
            nbodySubsystem<COL_OFFSET+17, 0>  nbody_inst17;
            nbodySubsystem<COL_OFFSET+18, 0>  nbody_inst18;
            nbodySubsystem<COL_OFFSET+19, 0>  nbody_inst19;
            nbodySubsystem<COL_OFFSET+20, 0>  nbody_inst20;
            nbodySubsystem<COL_OFFSET+21, 0>  nbody_inst21;
            nbodySubsystem<COL_OFFSET+22, 0>  nbody_inst22;
            nbodySubsystem<COL_OFFSET+23, 0>  nbody_inst23;
            nbodySubsystem<COL_OFFSET+24, 0>  nbody_inst24;
            nbodySubsystem<COL_OFFSET+25, 0>  nbody_inst25;
            nbodySubsystem<COL_OFFSET+26, 0>  nbody_inst26;
            nbodySubsystem<COL_OFFSET+27, 0>  nbody_inst27;
            nbodySubsystem<COL_OFFSET+28, 0>  nbody_inst28;
            nbodySubsystem<COL_OFFSET+29, 0>  nbody_inst29;
            nbodySubsystem<COL_OFFSET+30, 0>  nbody_inst30;
            nbodySubsystem<COL_OFFSET+31, 0>  nbody_inst31;
            nbodySubsystem<COL_OFFSET+32, 0>  nbody_inst32;
            nbodySubsystem<COL_OFFSET+33, 0>  nbody_inst33;
            nbodySubsystem<COL_OFFSET+34, 0>  nbody_inst34;
            nbodySubsystem<COL_OFFSET+35, 0>  nbody_inst35;
            nbodySubsystem<COL_OFFSET+36, 0>  nbody_inst36;
            nbodySubsystem<COL_OFFSET+37, 0>  nbody_inst37;
            nbodySubsystem<COL_OFFSET+38, 0>  nbody_inst38;
            nbodySubsystem<COL_OFFSET+39, 0>  nbody_inst39;
            nbodySubsystem<COL_OFFSET+40, 0>  nbody_inst40;
            nbodySubsystem<COL_OFFSET+41, 0>  nbody_inst41;
            nbodySubsystem<COL_OFFSET+42, 0>  nbody_inst42;
            nbodySubsystem<COL_OFFSET+43, 0>  nbody_inst43;
            nbodySubsystem<COL_OFFSET+44, 0>  nbody_inst44;
            nbodySubsystem<COL_OFFSET+45, 0>  nbody_inst45;
            nbodySubsystem<COL_OFFSET+46, 0>  nbody_inst46;
            nbodySubsystem<COL_OFFSET+47, 0>  nbody_inst47;
            nbodySubsystem<COL_OFFSET+48, 0>  nbody_inst48;
            nbodySubsystem<COL_OFFSET+49, 0>  nbody_inst49;

            //COL 0-49, ROW 4
            nbodySubsystem<COL_OFFSET+0, 4>  nbody_inst50;
            nbodySubsystem<COL_OFFSET+1, 4>  nbody_inst51;
            nbodySubsystem<COL_OFFSET+2, 4>  nbody_inst52;
            nbodySubsystem<COL_OFFSET+3, 4>  nbody_inst53;
            nbodySubsystem<COL_OFFSET+4, 4>  nbody_inst54;
            nbodySubsystem<COL_OFFSET+5, 4>  nbody_inst55;
            nbodySubsystem<COL_OFFSET+6, 4>  nbody_inst56;
            nbodySubsystem<COL_OFFSET+7, 4>  nbody_inst57;
            nbodySubsystem<COL_OFFSET+8, 4>  nbody_inst58;
            nbodySubsystem<COL_OFFSET+9, 4>  nbody_inst59;
            nbodySubsystem<COL_OFFSET+10, 4>  nbody_inst60;
            nbodySubsystem<COL_OFFSET+11, 4>  nbody_inst61;
            nbodySubsystem<COL_OFFSET+12, 4>  nbody_inst62;
            nbodySubsystem<COL_OFFSET+13, 4>  nbody_inst63;
            nbodySubsystem<COL_OFFSET+14, 4>  nbody_inst64;
            nbodySubsystem<COL_OFFSET+15, 4>  nbody_inst65;
            nbodySubsystem<COL_OFFSET+16, 4>  nbody_inst66;
            nbodySubsystem<COL_OFFSET+17, 4>  nbody_inst67;
            nbodySubsystem<COL_OFFSET+18, 4>  nbody_inst68;
            nbodySubsystem<COL_OFFSET+19, 4>  nbody_inst69;
            nbodySubsystem<COL_OFFSET+20, 4>  nbody_inst70;
            nbodySubsystem<COL_OFFSET+21, 4>  nbody_inst71;
            nbodySubsystem<COL_OFFSET+22, 4>  nbody_inst72;
            nbodySubsystem<COL_OFFSET+23, 4>  nbody_inst73;
            nbodySubsystem<COL_OFFSET+24, 4>  nbody_inst74;
            nbodySubsystem<COL_OFFSET+25, 4>  nbody_inst75;
            nbodySubsystem<COL_OFFSET+26, 4>  nbody_inst76;
            nbodySubsystem<COL_OFFSET+27, 4>  nbody_inst77;
            nbodySubsystem<COL_OFFSET+28, 4>  nbody_inst78;
            nbodySubsystem<COL_OFFSET+29, 4>  nbody_inst79;
            nbodySubsystem<COL_OFFSET+30, 4>  nbody_inst80;
            nbodySubsystem<COL_OFFSET+31, 4>  nbody_inst81;
            nbodySubsystem<COL_OFFSET+32, 4>  nbody_inst82;
            nbodySubsystem<COL_OFFSET+33, 4>  nbody_inst83;
            nbodySubsystem<COL_OFFSET+34, 4>  nbody_inst84;
            nbodySubsystem<COL_OFFSET+35, 4>  nbody_inst85;
            nbodySubsystem<COL_OFFSET+36, 4>  nbody_inst86;
            nbodySubsystem<COL_OFFSET+37, 4>  nbody_inst87;
            nbodySubsystem<COL_OFFSET+38, 4>  nbody_inst88;
            nbodySubsystem<COL_OFFSET+39, 4>  nbody_inst89;
            nbodySubsystem<COL_OFFSET+40, 4>  nbody_inst90;
            nbodySubsystem<COL_OFFSET+41, 4>  nbody_inst91;
            nbodySubsystem<COL_OFFSET+42, 4>  nbody_inst92;
            nbodySubsystem<COL_OFFSET+43, 4>  nbody_inst93;
            nbodySubsystem<COL_OFFSET+44, 4>  nbody_inst94;
            nbodySubsystem<COL_OFFSET+45, 4>  nbody_inst95;
            nbodySubsystem<COL_OFFSET+46, 4>  nbody_inst96;
            nbodySubsystem<COL_OFFSET+47, 4>  nbody_inst97;
            nbodySubsystem<COL_OFFSET+48, 4>  nbody_inst98;
            nbodySubsystem<COL_OFFSET+49, 4>  nbody_inst99;

	nbodySystem() {

		//Connect all input j ports
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst0.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst1.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst2.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst3.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst4.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst5.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst6.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst7.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst8.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst9.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst10.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst11.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst12.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst13.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst14.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst15.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst16.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst17.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst18.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst19.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst20.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst21.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst22.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst23.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst24.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst25.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst26.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst27.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst28.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst29.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst30.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst31.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst32.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst33.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst34.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst35.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst36.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst37.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst38.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst39.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst40.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst41.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst42.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst43.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst44.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst45.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst46.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst47.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst48.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst49.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst50.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst51.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst52.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst53.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst54.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst55.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst56.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst57.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst58.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst59.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst60.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst61.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst62.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst63.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst64.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst65.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst66.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst67.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst68.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst69.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst70.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst71.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst72.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst73.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst74.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst75.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst76.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst77.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst78.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst79.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst80.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst81.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst82.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst83.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst84.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst85.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst86.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst87.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst88.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst89.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst90.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst91.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst92.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst93.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst94.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst95.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst96.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst97.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst98.in[1]);
		connect< stream, window<WINDOW_SIZE_J > > (in_j, nbody_inst99.in[1]);

		//Connect all input i ports
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[0], nbody_inst0.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[1], nbody_inst1.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[2], nbody_inst2.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[3], nbody_inst3.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[4], nbody_inst4.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[5], nbody_inst5.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[6], nbody_inst6.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[7], nbody_inst7.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[8], nbody_inst8.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[9], nbody_inst9.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[10], nbody_inst10.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[11], nbody_inst11.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[12], nbody_inst12.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[13], nbody_inst13.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[14], nbody_inst14.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[15], nbody_inst15.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[16], nbody_inst16.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[17], nbody_inst17.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[18], nbody_inst18.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[19], nbody_inst19.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[20], nbody_inst20.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[21], nbody_inst21.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[22], nbody_inst22.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[23], nbody_inst23.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[24], nbody_inst24.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[25], nbody_inst25.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[26], nbody_inst26.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[27], nbody_inst27.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[28], nbody_inst28.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[29], nbody_inst29.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[30], nbody_inst30.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[31], nbody_inst31.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[32], nbody_inst32.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[33], nbody_inst33.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[34], nbody_inst34.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[35], nbody_inst35.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[36], nbody_inst36.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[37], nbody_inst37.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[38], nbody_inst38.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[39], nbody_inst39.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[40], nbody_inst40.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[41], nbody_inst41.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[42], nbody_inst42.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[43], nbody_inst43.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[44], nbody_inst44.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[45], nbody_inst45.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[46], nbody_inst46.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[47], nbody_inst47.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[48], nbody_inst48.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[49], nbody_inst49.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[50], nbody_inst50.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[51], nbody_inst51.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[52], nbody_inst52.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[53], nbody_inst53.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[54], nbody_inst54.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[55], nbody_inst55.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[56], nbody_inst56.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[57], nbody_inst57.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[58], nbody_inst58.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[59], nbody_inst59.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[60], nbody_inst60.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[61], nbody_inst61.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[62], nbody_inst62.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[63], nbody_inst63.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[64], nbody_inst64.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[65], nbody_inst65.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[66], nbody_inst66.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[67], nbody_inst67.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[68], nbody_inst68.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[69], nbody_inst69.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[70], nbody_inst70.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[71], nbody_inst71.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[72], nbody_inst72.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[73], nbody_inst73.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[74], nbody_inst74.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[75], nbody_inst75.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[76], nbody_inst76.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[77], nbody_inst77.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[78], nbody_inst78.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[79], nbody_inst79.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[80], nbody_inst80.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[81], nbody_inst81.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[82], nbody_inst82.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[83], nbody_inst83.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[84], nbody_inst84.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[85], nbody_inst85.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[86], nbody_inst86.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[87], nbody_inst87.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[88], nbody_inst88.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[89], nbody_inst89.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[90], nbody_inst90.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[91], nbody_inst91.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[92], nbody_inst92.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[93], nbody_inst93.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[94], nbody_inst94.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[95], nbody_inst95.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[96], nbody_inst96.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[97], nbody_inst97.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[98], nbody_inst98.in[0]);	
		connect< pktstream, window<WINDOW_SIZE_I > >(in_i[99], nbody_inst99.in[0]);	

		//Connect all output ports
		connect< pktstream > (nbody_inst0.out[0], out[0]);
		connect< pktstream > (nbody_inst1.out[0], out[1]);
		connect< pktstream > (nbody_inst2.out[0], out[2]);
		connect< pktstream > (nbody_inst3.out[0], out[3]);
		connect< pktstream > (nbody_inst4.out[0], out[4]);
		connect< pktstream > (nbody_inst5.out[0], out[5]);
		connect< pktstream > (nbody_inst6.out[0], out[6]);
		connect< pktstream > (nbody_inst7.out[0], out[7]);
		connect< pktstream > (nbody_inst8.out[0], out[8]);
		connect< pktstream > (nbody_inst9.out[0], out[9]);
		connect< pktstream > (nbody_inst10.out[0], out[10]);
		connect< pktstream > (nbody_inst11.out[0], out[11]);
		connect< pktstream > (nbody_inst12.out[0], out[12]);
		connect< pktstream > (nbody_inst13.out[0], out[13]);
		connect< pktstream > (nbody_inst14.out[0], out[14]);
		connect< pktstream > (nbody_inst15.out[0], out[15]);
		connect< pktstream > (nbody_inst16.out[0], out[16]);
		connect< pktstream > (nbody_inst17.out[0], out[17]);
		connect< pktstream > (nbody_inst18.out[0], out[18]);
		connect< pktstream > (nbody_inst19.out[0], out[19]);
		connect< pktstream > (nbody_inst20.out[0], out[20]);
		connect< pktstream > (nbody_inst21.out[0], out[21]);
		connect< pktstream > (nbody_inst22.out[0], out[22]);
		connect< pktstream > (nbody_inst23.out[0], out[23]);
		connect< pktstream > (nbody_inst24.out[0], out[24]);
		connect< pktstream > (nbody_inst25.out[0], out[25]);
		connect< pktstream > (nbody_inst26.out[0], out[26]);
		connect< pktstream > (nbody_inst27.out[0], out[27]);
		connect< pktstream > (nbody_inst28.out[0], out[28]);
		connect< pktstream > (nbody_inst29.out[0], out[29]);
		connect< pktstream > (nbody_inst30.out[0], out[30]);
		connect< pktstream > (nbody_inst31.out[0], out[31]);
		connect< pktstream > (nbody_inst32.out[0], out[32]);
		connect< pktstream > (nbody_inst33.out[0], out[33]);
		connect< pktstream > (nbody_inst34.out[0], out[34]);
		connect< pktstream > (nbody_inst35.out[0], out[35]);
		connect< pktstream > (nbody_inst36.out[0], out[36]);
		connect< pktstream > (nbody_inst37.out[0], out[37]);
		connect< pktstream > (nbody_inst38.out[0], out[38]);
		connect< pktstream > (nbody_inst39.out[0], out[39]);
		connect< pktstream > (nbody_inst40.out[0], out[40]);
		connect< pktstream > (nbody_inst41.out[0], out[41]);
		connect< pktstream > (nbody_inst42.out[0], out[42]);
		connect< pktstream > (nbody_inst43.out[0], out[43]);
		connect< pktstream > (nbody_inst44.out[0], out[44]);
		connect< pktstream > (nbody_inst45.out[0], out[45]);
		connect< pktstream > (nbody_inst46.out[0], out[46]);
		connect< pktstream > (nbody_inst47.out[0], out[47]);
		connect< pktstream > (nbody_inst48.out[0], out[48]);
		connect< pktstream > (nbody_inst49.out[0], out[49]);
		connect< pktstream > (nbody_inst50.out[0], out[50]);
		connect< pktstream > (nbody_inst51.out[0], out[51]);
		connect< pktstream > (nbody_inst52.out[0], out[52]);
		connect< pktstream > (nbody_inst53.out[0], out[53]);
		connect< pktstream > (nbody_inst54.out[0], out[54]);
		connect< pktstream > (nbody_inst55.out[0], out[55]);
		connect< pktstream > (nbody_inst56.out[0], out[56]);
		connect< pktstream > (nbody_inst57.out[0], out[57]);
		connect< pktstream > (nbody_inst58.out[0], out[58]);
		connect< pktstream > (nbody_inst59.out[0], out[59]);
		connect< pktstream > (nbody_inst60.out[0], out[60]);
		connect< pktstream > (nbody_inst61.out[0], out[61]);
		connect< pktstream > (nbody_inst62.out[0], out[62]);
		connect< pktstream > (nbody_inst63.out[0], out[63]);
		connect< pktstream > (nbody_inst64.out[0], out[64]);
		connect< pktstream > (nbody_inst65.out[0], out[65]);
		connect< pktstream > (nbody_inst66.out[0], out[66]);
		connect< pktstream > (nbody_inst67.out[0], out[67]);
		connect< pktstream > (nbody_inst68.out[0], out[68]);
		connect< pktstream > (nbody_inst69.out[0], out[69]);
		connect< pktstream > (nbody_inst70.out[0], out[70]);
		connect< pktstream > (nbody_inst71.out[0], out[71]);
		connect< pktstream > (nbody_inst72.out[0], out[72]);
		connect< pktstream > (nbody_inst73.out[0], out[73]);
		connect< pktstream > (nbody_inst74.out[0], out[74]);
		connect< pktstream > (nbody_inst75.out[0], out[75]);
		connect< pktstream > (nbody_inst76.out[0], out[76]);
		connect< pktstream > (nbody_inst77.out[0], out[77]);
		connect< pktstream > (nbody_inst78.out[0], out[78]);
		connect< pktstream > (nbody_inst79.out[0], out[79]);
		connect< pktstream > (nbody_inst80.out[0], out[80]);
		connect< pktstream > (nbody_inst81.out[0], out[81]);
		connect< pktstream > (nbody_inst82.out[0], out[82]);
		connect< pktstream > (nbody_inst83.out[0], out[83]);
		connect< pktstream > (nbody_inst84.out[0], out[84]);
		connect< pktstream > (nbody_inst85.out[0], out[85]);
		connect< pktstream > (nbody_inst86.out[0], out[86]);
		connect< pktstream > (nbody_inst87.out[0], out[87]);
		connect< pktstream > (nbody_inst88.out[0], out[88]);
		connect< pktstream > (nbody_inst89.out[0], out[89]);
		connect< pktstream > (nbody_inst90.out[0], out[90]);
		connect< pktstream > (nbody_inst91.out[0], out[91]);
		connect< pktstream > (nbody_inst92.out[0], out[92]);
		connect< pktstream > (nbody_inst93.out[0], out[93]);
		connect< pktstream > (nbody_inst94.out[0], out[94]);
		connect< pktstream > (nbody_inst95.out[0], out[95]);
		connect< pktstream > (nbody_inst96.out[0], out[96]);
		connect< pktstream > (nbody_inst97.out[0], out[97]);
		connect< pktstream > (nbody_inst98.out[0], out[98]);
		connect< pktstream > (nbody_inst99.out[0], out[99]);
        
	}
};
        
