-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity stream_out is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    s_TREADY : IN STD_LOGIC;
    s_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    s_TVALID : OUT STD_LOGIC;
    s_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    s_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    s_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of stream_out is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "stream_out_stream_out,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=3.200000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.768500,HLS_SYN_LAT=2563,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=51,HLS_SYN_LUT=65,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv13_2 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000010";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv13_1400 : STD_LOGIC_VECTOR (12 downto 0) := "1010000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";

attribute shreg_extract : string;
    signal ap_rst_reg_2 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_2 : signal is "no";
    signal ap_rst_reg_1 : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_reg_1 : signal is "no";
    signal ap_rst_n_inv : STD_LOGIC := '1';
attribute shreg_extract of ap_rst_n_inv : signal is "no";
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal regslice_both_s_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln33_fu_180_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal cint16Input_address0 : STD_LOGIC_VECTOR (10 downto 0);
    signal cint16Input_q0 : STD_LOGIC_VECTOR (15 downto 0);
    signal cint16Input_address1 : STD_LOGIC_VECTOR (10 downto 0);
    signal cint16Input_q1 : STD_LOGIC_VECTOR (15 downto 0);
    signal s_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal x_data_fu_208_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln33_fu_144_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln36_fu_171_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i1_fu_78 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    signal i_fu_138_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i1_load : STD_LOGIC_VECTOR (12 downto 0);
    signal x_data2_fu_82 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal cint16Input_ce1_local : STD_LOGIC;
    signal cint16Input_ce0_local : STD_LOGIC;
    signal tmp_fu_153_p4 : STD_LOGIC_VECTOR (9 downto 0);
    signal or_ln_fu_163_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal x_data_1_fu_194_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln36_fu_204_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_continue_int : STD_LOGIC;
    signal s_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal s_TVALID_int_regslice : STD_LOGIC;
    signal s_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_s_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_s_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_s_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal s_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_s_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_s_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_s_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_s_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_s_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_condition_102 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component stream_out_cint16Input_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        address1 : IN STD_LOGIC_VECTOR (10 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;


    component stream_out_flow_control_loop_pipe_no_ap_cont IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;


    component stream_out_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    cint16Input_U : component stream_out_cint16Input_ROM_AUTO_1R
    generic map (
        DataWidth => 16,
        AddressRange => 2048,
        AddressWidth => 11)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => cint16Input_address0,
        ce0 => cint16Input_ce0_local,
        q0 => cint16Input_q0,
        address1 => cint16Input_address1,
        ce1 => cint16Input_ce1_local,
        q1 => cint16Input_q1);

    flow_control_loop_pipe_no_ap_cont_U : component stream_out_flow_control_loop_pipe_no_ap_cont
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => ap_const_logic_1,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_const_logic_0,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_const_logic_0);

    regslice_both_s_V_data_V_U : component stream_out_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_TDATA_int_regslice,
        vld_in => s_TVALID_int_regslice,
        ack_in => s_TREADY_int_regslice,
        data_out => s_TDATA,
        vld_out => regslice_both_s_V_data_V_U_vld_out,
        ack_out => s_TREADY,
        apdone_blk => regslice_both_s_V_data_V_U_apdone_blk);

    regslice_both_s_V_keep_V_U : component stream_out_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv4_F,
        vld_in => s_TVALID_int_regslice,
        ack_in => regslice_both_s_V_keep_V_U_ack_in_dummy,
        data_out => s_TKEEP,
        vld_out => regslice_both_s_V_keep_V_U_vld_out,
        ack_out => s_TREADY,
        apdone_blk => regslice_both_s_V_keep_V_U_apdone_blk);

    regslice_both_s_V_strb_V_U : component stream_out_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => s_TSTRB_int_regslice,
        vld_in => s_TVALID_int_regslice,
        ack_in => regslice_both_s_V_strb_V_U_ack_in_dummy,
        data_out => s_TSTRB,
        vld_out => regslice_both_s_V_strb_V_U_vld_out,
        ack_out => s_TREADY,
        apdone_blk => regslice_both_s_V_strb_V_U_apdone_blk);

    regslice_both_s_V_last_V_U : component stream_out_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => ap_const_lv1_0,
        vld_in => s_TVALID_int_regslice,
        ack_in => regslice_both_s_V_last_V_U_ack_in_dummy,
        data_out => s_TLAST,
        vld_out => regslice_both_s_V_last_V_U_vld_out,
        ack_out => s_TREADY,
        apdone_blk => regslice_both_s_V_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_rst_n_inv_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_n_inv <= ap_rst_reg_1;
        end if;
    end process;

    ap_rst_reg_1_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_rst_reg_1 <= ap_rst_reg_2;
        end if;
    end process;

    ap_rst_reg_2_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
                        ap_rst_reg_2 <= not(ap_rst_n);
        end if;
    end process;

    i1_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_102)) then
                i1_fu_78 <= i_fu_138_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                x_data2_fu_82 <= x_data_fu_208_p4;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_block_state2_pp0_stage0_iter1, ap_enable_reg_pp0_iter1, regslice_both_s_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage0_iter2, ap_enable_reg_pp0_iter2, ap_loop_exit_ready_pp0_iter2_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_s_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_block_state2_pp0_stage0_iter1, ap_enable_reg_pp0_iter1, regslice_both_s_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage0_iter2, ap_enable_reg_pp0_iter2, ap_loop_exit_ready_pp0_iter2_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_s_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_block_state2_pp0_stage0_iter1, ap_enable_reg_pp0_iter1, regslice_both_s_V_data_V_U_apdone_blk, ap_block_state3_pp0_stage0_iter2, ap_enable_reg_pp0_iter2, ap_loop_exit_ready_pp0_iter2_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (regslice_both_s_V_data_V_U_apdone_blk = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(s_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (s_TREADY_int_regslice = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(regslice_both_s_V_data_V_U_apdone_blk, s_TREADY_int_regslice)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((regslice_both_s_V_data_V_U_apdone_blk = ap_const_logic_1) or (s_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_condition_102_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
                ap_condition_102 <= ((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln33_fu_180_p2)
    begin
        if (((icmp_ln33_fu_180_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_const_logic_1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i1_fu_78, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i1_load <= ap_const_lv13_0;
        else 
            ap_sig_allocacmp_i1_load <= i1_fu_78;
        end if; 
    end process;

    cint16Input_address0 <= zext_ln36_fu_171_p1(11 - 1 downto 0);
    cint16Input_address1 <= zext_ln33_fu_144_p1(11 - 1 downto 0);

    cint16Input_ce0_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cint16Input_ce0_local <= ap_const_logic_1;
        else 
            cint16Input_ce0_local <= ap_const_logic_0;
        end if; 
    end process;


    cint16Input_ce1_local_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            cint16Input_ce1_local <= ap_const_logic_1;
        else 
            cint16Input_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_138_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i1_load) + unsigned(ap_const_lv13_2));
    icmp_ln33_fu_180_p2 <= "1" when (unsigned(i_fu_138_p2) < unsigned(ap_const_lv13_1400)) else "0";
    or_ln_fu_163_p3 <= (tmp_fu_153_p4 & ap_const_lv1_1);

    s_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_block_pp0_stage0, s_TREADY_int_regslice)
    begin
        if ((((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1)) or ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0)))) then 
            s_TDATA_blk_n <= s_TREADY_int_regslice;
        else 
            s_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    s_TDATA_int_regslice <= (sext_ln36_fu_204_p1 & x_data_1_fu_194_p4(15 downto 0));
    s_TSTRB_int_regslice <= "XXXX";
    s_TVALID <= regslice_both_s_V_data_V_U_vld_out;

    s_TVALID_int_regslice_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            s_TVALID_int_regslice <= ap_const_logic_1;
        else 
            s_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln36_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cint16Input_q0),17));

    tmp_fu_153_p4 <= ap_sig_allocacmp_i1_load(10 downto 1);
    x_data_1_fu_194_p4 <= (x_data2_fu_82(31 downto 16) & cint16Input_q1);
    x_data_fu_208_p4 <= (sext_ln36_fu_204_p1 & x_data_1_fu_194_p4(15 downto 0));
    zext_ln33_fu_144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i1_load),64));
    zext_ln36_fu_171_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln_fu_163_p3),64));
end behav;
