#!/bin/bash
# Copyright (C) Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT

echo " "
echo "************************************************************************ "
echo " "

grep -e "Repetition count" AIECompiler.log

echo " "
echo "************************************************************************ "
echo " "
