% Copyright © 2023 Advanced Micro Devices, Inc. All rights reserved.
% SPDX-License-Identifier: MIT

%%
clear all
close all
clc

%% data

% load input data
I = load('vector_inputs.txt');

% load output data generated by target board
O = load('vector_out.txt');

% reference result computed by MATLAB
R = I(:,1) + I(:,2);

%% check results

diff_R_O1 = abs(diff(R-O(:,1))); %ref vs. ARM CPU
diff_R_O2 = abs(diff(R-O(:,2))); %ref vs. PL kernel
diff_O1_O2 = abs(diff(O(:,1)-O(:,2))); % ARM CPU vs. PL kernel

sum_abs_err = sum(diff_R_O1(:)) + sum(diff_R_O2(:)) + sum(diff_O1_O2(:))


figure; plot(diff_O1_O2); grid; title 'diff O1 vs O2'
figure; plot(diff_R_O2);  grid; title 'diff M  vs O2'
figure; plot(diff_R_O1);  grid; title 'diff M  vs O1'
