/*Copyright (C) 2024, Advanced Micro Devices, Inc. All rights reserved.
SPDX-License-Identifier: MIT
*/

#include "nbody_subsystem.h"

#define NUM_INSTANCES 100

using namespace adf;


template <int COL_OFFSET>
class nbodySystem : public adf::graph {
	
public:
	input_plio in_i[NUM_INSTANCES];
	input_plio in_j; 	
	output_plio out_i[NUM_INSTANCES];

	     
            //COL 0-49, ROW 0
            nbodySubsystem<COL_OFFSET+0, 0>  nbody_inst0;
            nbodySubsystem<COL_OFFSET+1, 0>  nbody_inst1;
            nbodySubsystem<COL_OFFSET+2, 0>  nbody_inst2;
            nbodySubsystem<COL_OFFSET+3, 0>  nbody_inst3;
            nbodySubsystem<COL_OFFSET+4, 0>  nbody_inst4;
            nbodySubsystem<COL_OFFSET+5, 0>  nbody_inst5;
            nbodySubsystem<COL_OFFSET+6, 0>  nbody_inst6;
            nbodySubsystem<COL_OFFSET+7, 0>  nbody_inst7;
            nbodySubsystem<COL_OFFSET+8, 0>  nbody_inst8;
            nbodySubsystem<COL_OFFSET+9, 0>  nbody_inst9;
            nbodySubsystem<COL_OFFSET+10, 0>  nbody_inst10;
            nbodySubsystem<COL_OFFSET+11, 0>  nbody_inst11;
            nbodySubsystem<COL_OFFSET+12, 0>  nbody_inst12;
            nbodySubsystem<COL_OFFSET+13, 0>  nbody_inst13;
            nbodySubsystem<COL_OFFSET+14, 0>  nbody_inst14;
            nbodySubsystem<COL_OFFSET+15, 0>  nbody_inst15;
            nbodySubsystem<COL_OFFSET+16, 0>  nbody_inst16;
            nbodySubsystem<COL_OFFSET+17, 0>  nbody_inst17;
            nbodySubsystem<COL_OFFSET+18, 0>  nbody_inst18;
            nbodySubsystem<COL_OFFSET+19, 0>  nbody_inst19;
            nbodySubsystem<COL_OFFSET+20, 0>  nbody_inst20;
            nbodySubsystem<COL_OFFSET+21, 0>  nbody_inst21;
            nbodySubsystem<COL_OFFSET+22, 0>  nbody_inst22;
            nbodySubsystem<COL_OFFSET+23, 0>  nbody_inst23;
            nbodySubsystem<COL_OFFSET+24, 0>  nbody_inst24;
            nbodySubsystem<COL_OFFSET+25, 0>  nbody_inst25;
            nbodySubsystem<COL_OFFSET+26, 0>  nbody_inst26;
            nbodySubsystem<COL_OFFSET+27, 0>  nbody_inst27;
            nbodySubsystem<COL_OFFSET+28, 0>  nbody_inst28;
            nbodySubsystem<COL_OFFSET+29, 0>  nbody_inst29;
            nbodySubsystem<COL_OFFSET+30, 0>  nbody_inst30;
            nbodySubsystem<COL_OFFSET+31, 0>  nbody_inst31;
            nbodySubsystem<COL_OFFSET+32, 0>  nbody_inst32;
            nbodySubsystem<COL_OFFSET+33, 0>  nbody_inst33;
            nbodySubsystem<COL_OFFSET+34, 0>  nbody_inst34;
            nbodySubsystem<COL_OFFSET+35, 0>  nbody_inst35;
            nbodySubsystem<COL_OFFSET+36, 0>  nbody_inst36;
            nbodySubsystem<COL_OFFSET+37, 0>  nbody_inst37;
            nbodySubsystem<COL_OFFSET+38, 0>  nbody_inst38;
            nbodySubsystem<COL_OFFSET+39, 0>  nbody_inst39;
            nbodySubsystem<COL_OFFSET+40, 0>  nbody_inst40;
            nbodySubsystem<COL_OFFSET+41, 0>  nbody_inst41;
            nbodySubsystem<COL_OFFSET+42, 0>  nbody_inst42;
            nbodySubsystem<COL_OFFSET+43, 0>  nbody_inst43;
            nbodySubsystem<COL_OFFSET+44, 0>  nbody_inst44;
            nbodySubsystem<COL_OFFSET+45, 0>  nbody_inst45;
            nbodySubsystem<COL_OFFSET+46, 0>  nbody_inst46;
            nbodySubsystem<COL_OFFSET+47, 0>  nbody_inst47;
            nbodySubsystem<COL_OFFSET+48, 0>  nbody_inst48;
            nbodySubsystem<COL_OFFSET+49, 0>  nbody_inst49;

            //COL 0-49, ROW 4
            nbodySubsystem<COL_OFFSET+0, 4>  nbody_inst50;
            nbodySubsystem<COL_OFFSET+1, 4>  nbody_inst51;
            nbodySubsystem<COL_OFFSET+2, 4>  nbody_inst52;
            nbodySubsystem<COL_OFFSET+3, 4>  nbody_inst53;
            nbodySubsystem<COL_OFFSET+4, 4>  nbody_inst54;
            nbodySubsystem<COL_OFFSET+5, 4>  nbody_inst55;
            nbodySubsystem<COL_OFFSET+6, 4>  nbody_inst56;
            nbodySubsystem<COL_OFFSET+7, 4>  nbody_inst57;
            nbodySubsystem<COL_OFFSET+8, 4>  nbody_inst58;
            nbodySubsystem<COL_OFFSET+9, 4>  nbody_inst59;
            nbodySubsystem<COL_OFFSET+10, 4>  nbody_inst60;
            nbodySubsystem<COL_OFFSET+11, 4>  nbody_inst61;
            nbodySubsystem<COL_OFFSET+12, 4>  nbody_inst62;
            nbodySubsystem<COL_OFFSET+13, 4>  nbody_inst63;
            nbodySubsystem<COL_OFFSET+14, 4>  nbody_inst64;
            nbodySubsystem<COL_OFFSET+15, 4>  nbody_inst65;
            nbodySubsystem<COL_OFFSET+16, 4>  nbody_inst66;
            nbodySubsystem<COL_OFFSET+17, 4>  nbody_inst67;
            nbodySubsystem<COL_OFFSET+18, 4>  nbody_inst68;
            nbodySubsystem<COL_OFFSET+19, 4>  nbody_inst69;
            nbodySubsystem<COL_OFFSET+20, 4>  nbody_inst70;
            nbodySubsystem<COL_OFFSET+21, 4>  nbody_inst71;
            nbodySubsystem<COL_OFFSET+22, 4>  nbody_inst72;
            nbodySubsystem<COL_OFFSET+23, 4>  nbody_inst73;
            nbodySubsystem<COL_OFFSET+24, 4>  nbody_inst74;
            nbodySubsystem<COL_OFFSET+25, 4>  nbody_inst75;
            nbodySubsystem<COL_OFFSET+26, 4>  nbody_inst76;
            nbodySubsystem<COL_OFFSET+27, 4>  nbody_inst77;
            nbodySubsystem<COL_OFFSET+28, 4>  nbody_inst78;
            nbodySubsystem<COL_OFFSET+29, 4>  nbody_inst79;
            nbodySubsystem<COL_OFFSET+30, 4>  nbody_inst80;
            nbodySubsystem<COL_OFFSET+31, 4>  nbody_inst81;
            nbodySubsystem<COL_OFFSET+32, 4>  nbody_inst82;
            nbodySubsystem<COL_OFFSET+33, 4>  nbody_inst83;
            nbodySubsystem<COL_OFFSET+34, 4>  nbody_inst84;
            nbodySubsystem<COL_OFFSET+35, 4>  nbody_inst85;
            nbodySubsystem<COL_OFFSET+36, 4>  nbody_inst86;
            nbodySubsystem<COL_OFFSET+37, 4>  nbody_inst87;
            nbodySubsystem<COL_OFFSET+38, 4>  nbody_inst88;
            nbodySubsystem<COL_OFFSET+39, 4>  nbody_inst89;
            nbodySubsystem<COL_OFFSET+40, 4>  nbody_inst90;
            nbodySubsystem<COL_OFFSET+41, 4>  nbody_inst91;
            nbodySubsystem<COL_OFFSET+42, 4>  nbody_inst92;
            nbodySubsystem<COL_OFFSET+43, 4>  nbody_inst93;
            nbodySubsystem<COL_OFFSET+44, 4>  nbody_inst94;
            nbodySubsystem<COL_OFFSET+45, 4>  nbody_inst95;
            nbodySubsystem<COL_OFFSET+46, 4>  nbody_inst96;
            nbodySubsystem<COL_OFFSET+47, 4>  nbody_inst97;
            nbodySubsystem<COL_OFFSET+48, 4>  nbody_inst98;
            nbodySubsystem<COL_OFFSET+49, 4>  nbody_inst99;
	nbodySystem() {
       
		in_j  = input_plio::create("in_j",  adf::plio_32_bits, "../../data/input_j.txt",400);
		for(unsigned k=0;k<100;k++){      
			//input i PLIOs
			in_i[k]=input_plio::create("in_i"+std::to_string(k), adf::plio_32_bits, "data/input_i"+std::to_string(k)+".txt",400);
		  }
                for(unsigned l=0;l<100;l++){
			//output PLIOs
			out_i[l] = output_plio::create("out_i"+std::to_string(l),adf::plio_32_bits, "data/output_i"+std::to_string(l)+".txt",400);
    		}

		//Connect all input j ports
		connect(in_j.out[0], nbody_inst0.data_in[1]);  
		connect(in_j.out[0], nbody_inst1.data_in[1]);  
		connect(in_j.out[0], nbody_inst2.data_in[1]);  
		connect(in_j.out[0], nbody_inst3.data_in[1]);  
		connect(in_j.out[0], nbody_inst4.data_in[1]);  
		connect(in_j.out[0], nbody_inst5.data_in[1]);  
		connect(in_j.out[0], nbody_inst6.data_in[1]);  
		connect(in_j.out[0], nbody_inst7.data_in[1]);  
		connect(in_j.out[0], nbody_inst8.data_in[1]);  
		connect(in_j.out[0], nbody_inst9.data_in[1]);  
		connect(in_j.out[0], nbody_inst10.data_in[1]); 
		connect(in_j.out[0], nbody_inst11.data_in[1]); 
		connect(in_j.out[0], nbody_inst12.data_in[1]); 
		connect(in_j.out[0], nbody_inst13.data_in[1]); 
		connect(in_j.out[0], nbody_inst14.data_in[1]); 
		connect(in_j.out[0], nbody_inst15.data_in[1]); 
		connect(in_j.out[0], nbody_inst16.data_in[1]); 
		connect(in_j.out[0], nbody_inst17.data_in[1]); 
		connect(in_j.out[0], nbody_inst18.data_in[1]); 
		connect(in_j.out[0], nbody_inst19.data_in[1]); 
		connect(in_j.out[0], nbody_inst20.data_in[1]); 
		connect(in_j.out[0], nbody_inst21.data_in[1]); 
		connect(in_j.out[0], nbody_inst22.data_in[1]); 
		connect(in_j.out[0], nbody_inst23.data_in[1]); 
		connect(in_j.out[0], nbody_inst24.data_in[1]); 
		connect(in_j.out[0], nbody_inst25.data_in[1]); 
		connect(in_j.out[0], nbody_inst26.data_in[1]); 
		connect(in_j.out[0], nbody_inst27.data_in[1]); 
		connect(in_j.out[0], nbody_inst28.data_in[1]); 
		connect(in_j.out[0], nbody_inst29.data_in[1]); 
		connect(in_j.out[0], nbody_inst30.data_in[1]); 
		connect(in_j.out[0], nbody_inst31.data_in[1]); 
		connect(in_j.out[0], nbody_inst32.data_in[1]); 
		connect(in_j.out[0], nbody_inst33.data_in[1]); 
		connect(in_j.out[0], nbody_inst34.data_in[1]); 
		connect(in_j.out[0], nbody_inst35.data_in[1]); 
		connect(in_j.out[0], nbody_inst36.data_in[1]); 
		connect(in_j.out[0], nbody_inst37.data_in[1]); 
		connect(in_j.out[0], nbody_inst38.data_in[1]); 
		connect(in_j.out[0], nbody_inst39.data_in[1]); 
		connect(in_j.out[0], nbody_inst40.data_in[1]); 
		connect(in_j.out[0], nbody_inst41.data_in[1]); 
		connect(in_j.out[0], nbody_inst42.data_in[1]); 
		connect(in_j.out[0], nbody_inst43.data_in[1]); 
		connect(in_j.out[0], nbody_inst44.data_in[1]); 
		connect(in_j.out[0], nbody_inst45.data_in[1]); 
		connect(in_j.out[0], nbody_inst46.data_in[1]); 
		connect(in_j.out[0], nbody_inst47.data_in[1]); 
		connect(in_j.out[0], nbody_inst48.data_in[1]); 
		connect(in_j.out[0], nbody_inst49.data_in[1]); 
		connect(in_j.out[0], nbody_inst50.data_in[1]); 
		connect(in_j.out[0], nbody_inst51.data_in[1]); 
		connect(in_j.out[0], nbody_inst52.data_in[1]); 
		connect(in_j.out[0], nbody_inst53.data_in[1]); 
		connect(in_j.out[0], nbody_inst54.data_in[1]); 
		connect(in_j.out[0], nbody_inst55.data_in[1]); 
		connect(in_j.out[0], nbody_inst56.data_in[1]); 
		connect(in_j.out[0], nbody_inst57.data_in[1]); 
		connect(in_j.out[0], nbody_inst58.data_in[1]); 
		connect(in_j.out[0], nbody_inst59.data_in[1]); 
		connect(in_j.out[0], nbody_inst60.data_in[1]); 
		connect(in_j.out[0], nbody_inst61.data_in[1]); 
		connect(in_j.out[0], nbody_inst62.data_in[1]); 
		connect(in_j.out[0], nbody_inst63.data_in[1]); 
		connect(in_j.out[0], nbody_inst64.data_in[1]); 
		connect(in_j.out[0], nbody_inst65.data_in[1]); 
		connect(in_j.out[0], nbody_inst66.data_in[1]); 
		connect(in_j.out[0], nbody_inst67.data_in[1]); 
		connect(in_j.out[0], nbody_inst68.data_in[1]); 
		connect(in_j.out[0], nbody_inst69.data_in[1]); 
		connect(in_j.out[0], nbody_inst70.data_in[1]); 
		connect(in_j.out[0], nbody_inst71.data_in[1]); 
		connect(in_j.out[0], nbody_inst72.data_in[1]); 
		connect(in_j.out[0], nbody_inst73.data_in[1]); 
		connect(in_j.out[0], nbody_inst74.data_in[1]); 
		connect(in_j.out[0], nbody_inst75.data_in[1]); 
		connect(in_j.out[0], nbody_inst76.data_in[1]); 
		connect(in_j.out[0], nbody_inst77.data_in[1]); 
		connect(in_j.out[0], nbody_inst78.data_in[1]); 
		connect(in_j.out[0], nbody_inst79.data_in[1]); 
		connect(in_j.out[0], nbody_inst80.data_in[1]); 
		connect(in_j.out[0], nbody_inst81.data_in[1]); 
		connect(in_j.out[0], nbody_inst82.data_in[1]); 
		connect(in_j.out[0], nbody_inst83.data_in[1]); 
		connect(in_j.out[0], nbody_inst84.data_in[1]); 
		connect(in_j.out[0], nbody_inst85.data_in[1]); 
		connect(in_j.out[0], nbody_inst86.data_in[1]); 
		connect(in_j.out[0], nbody_inst87.data_in[1]); 
		connect(in_j.out[0], nbody_inst88.data_in[1]); 
		connect(in_j.out[0], nbody_inst89.data_in[1]); 
		connect(in_j.out[0], nbody_inst90.data_in[1]); 
		connect(in_j.out[0], nbody_inst91.data_in[1]); 
		connect(in_j.out[0], nbody_inst92.data_in[1]); 
		connect(in_j.out[0], nbody_inst93.data_in[1]); 
		connect(in_j.out[0], nbody_inst94.data_in[1]); 
		connect(in_j.out[0], nbody_inst95.data_in[1]); 
		connect(in_j.out[0], nbody_inst96.data_in[1]); 
		connect(in_j.out[0], nbody_inst97.data_in[1]); 
		connect(in_j.out[0], nbody_inst98.data_in[1]); 
		connect(in_j.out[0], nbody_inst99.data_in[1]); 

		//Connect all input i ports
		connect(in_i[0].out[0], nbody_inst0.data_in[0]);   
		connect(in_i[1].out[0], nbody_inst1.data_in[0]);   
		connect(in_i[2].out[0], nbody_inst2.data_in[0]);   
		connect(in_i[3].out[0], nbody_inst3.data_in[0]);   
		connect(in_i[4].out[0], nbody_inst4.data_in[0]);   
		connect(in_i[5].out[0], nbody_inst5.data_in[0]);   
		connect(in_i[6].out[0], nbody_inst6.data_in[0]);   
		connect(in_i[7].out[0], nbody_inst7.data_in[0]);   
		connect(in_i[8].out[0], nbody_inst8.data_in[0]);   
		connect(in_i[9].out[0], nbody_inst9.data_in[0]);   
		connect(in_i[10].out[0], nbody_inst10.data_in[0]); 
		connect(in_i[11].out[0], nbody_inst11.data_in[0]); 
		connect(in_i[12].out[0], nbody_inst12.data_in[0]); 
		connect(in_i[13].out[0], nbody_inst13.data_in[0]); 
		connect(in_i[14].out[0], nbody_inst14.data_in[0]); 
		connect(in_i[15].out[0], nbody_inst15.data_in[0]); 
		connect(in_i[16].out[0], nbody_inst16.data_in[0]); 
		connect(in_i[17].out[0], nbody_inst17.data_in[0]); 
		connect(in_i[18].out[0], nbody_inst18.data_in[0]); 
		connect(in_i[19].out[0], nbody_inst19.data_in[0]); 
		connect(in_i[20].out[0], nbody_inst20.data_in[0]); 
		connect(in_i[21].out[0], nbody_inst21.data_in[0]); 
		connect(in_i[22].out[0], nbody_inst22.data_in[0]); 
		connect(in_i[23].out[0], nbody_inst23.data_in[0]); 
		connect(in_i[24].out[0], nbody_inst24.data_in[0]); 
		connect(in_i[25].out[0], nbody_inst25.data_in[0]); 
		connect(in_i[26].out[0], nbody_inst26.data_in[0]); 
		connect(in_i[27].out[0], nbody_inst27.data_in[0]); 
		connect(in_i[28].out[0], nbody_inst28.data_in[0]); 
		connect(in_i[29].out[0], nbody_inst29.data_in[0]); 
		connect(in_i[30].out[0], nbody_inst30.data_in[0]); 
		connect(in_i[31].out[0], nbody_inst31.data_in[0]); 
		connect(in_i[32].out[0], nbody_inst32.data_in[0]); 
		connect(in_i[33].out[0], nbody_inst33.data_in[0]); 
		connect(in_i[34].out[0], nbody_inst34.data_in[0]); 
		connect(in_i[35].out[0], nbody_inst35.data_in[0]); 
		connect(in_i[36].out[0], nbody_inst36.data_in[0]); 
		connect(in_i[37].out[0], nbody_inst37.data_in[0]); 
		connect(in_i[38].out[0], nbody_inst38.data_in[0]); 
		connect(in_i[39].out[0], nbody_inst39.data_in[0]); 
		connect(in_i[40].out[0], nbody_inst40.data_in[0]); 
		connect(in_i[41].out[0], nbody_inst41.data_in[0]); 
		connect(in_i[42].out[0], nbody_inst42.data_in[0]); 
		connect(in_i[43].out[0], nbody_inst43.data_in[0]); 
		connect(in_i[44].out[0], nbody_inst44.data_in[0]); 
		connect(in_i[45].out[0], nbody_inst45.data_in[0]); 
		connect(in_i[46].out[0], nbody_inst46.data_in[0]); 
		connect(in_i[47].out[0], nbody_inst47.data_in[0]); 
		connect(in_i[48].out[0], nbody_inst48.data_in[0]); 
		connect(in_i[49].out[0], nbody_inst49.data_in[0]); 
		connect(in_i[50].out[0], nbody_inst50.data_in[0]); 
		connect(in_i[51].out[0], nbody_inst51.data_in[0]); 
		connect(in_i[52].out[0], nbody_inst52.data_in[0]); 
		connect(in_i[53].out[0], nbody_inst53.data_in[0]); 
		connect(in_i[54].out[0], nbody_inst54.data_in[0]); 
		connect(in_i[55].out[0], nbody_inst55.data_in[0]); 
		connect(in_i[56].out[0], nbody_inst56.data_in[0]); 
		connect(in_i[57].out[0], nbody_inst57.data_in[0]); 
		connect(in_i[58].out[0], nbody_inst58.data_in[0]); 
		connect(in_i[59].out[0], nbody_inst59.data_in[0]); 
		connect(in_i[60].out[0], nbody_inst60.data_in[0]); 
		connect(in_i[61].out[0], nbody_inst61.data_in[0]); 
		connect(in_i[62].out[0], nbody_inst62.data_in[0]); 
		connect(in_i[63].out[0], nbody_inst63.data_in[0]); 
		connect(in_i[64].out[0], nbody_inst64.data_in[0]); 
		connect(in_i[65].out[0], nbody_inst65.data_in[0]); 
		connect(in_i[66].out[0], nbody_inst66.data_in[0]); 
		connect(in_i[67].out[0], nbody_inst67.data_in[0]); 
		connect(in_i[68].out[0], nbody_inst68.data_in[0]); 
		connect(in_i[69].out[0], nbody_inst69.data_in[0]); 
		connect(in_i[70].out[0], nbody_inst70.data_in[0]); 
		connect(in_i[71].out[0], nbody_inst71.data_in[0]); 
		connect(in_i[72].out[0], nbody_inst72.data_in[0]); 
		connect(in_i[73].out[0], nbody_inst73.data_in[0]); 
		connect(in_i[74].out[0], nbody_inst74.data_in[0]); 
		connect(in_i[75].out[0], nbody_inst75.data_in[0]); 
		connect(in_i[76].out[0], nbody_inst76.data_in[0]); 
		connect(in_i[77].out[0], nbody_inst77.data_in[0]); 
		connect(in_i[78].out[0], nbody_inst78.data_in[0]); 
		connect(in_i[79].out[0], nbody_inst79.data_in[0]); 
		connect(in_i[80].out[0], nbody_inst80.data_in[0]); 
		connect(in_i[81].out[0], nbody_inst81.data_in[0]); 
		connect(in_i[82].out[0], nbody_inst82.data_in[0]); 
		connect(in_i[83].out[0], nbody_inst83.data_in[0]); 
		connect(in_i[84].out[0], nbody_inst84.data_in[0]); 
		connect(in_i[85].out[0], nbody_inst85.data_in[0]); 
		connect(in_i[86].out[0], nbody_inst86.data_in[0]); 
		connect(in_i[87].out[0], nbody_inst87.data_in[0]); 
		connect(in_i[88].out[0], nbody_inst88.data_in[0]); 
		connect(in_i[89].out[0], nbody_inst89.data_in[0]); 
		connect(in_i[90].out[0], nbody_inst90.data_in[0]); 
		connect(in_i[91].out[0], nbody_inst91.data_in[0]); 
		connect(in_i[92].out[0], nbody_inst92.data_in[0]); 
		connect(in_i[93].out[0], nbody_inst93.data_in[0]); 
		connect(in_i[94].out[0], nbody_inst94.data_in[0]); 
		connect(in_i[95].out[0], nbody_inst95.data_in[0]); 
		connect(in_i[96].out[0], nbody_inst96.data_in[0]); 
		connect(in_i[97].out[0], nbody_inst97.data_in[0]); 
		connect(in_i[98].out[0], nbody_inst98.data_in[0]); 
		connect(in_i[99].out[0], nbody_inst99.data_in[0]); 
		
		//Connect all output ports
		connect<pktstream>(nbody_inst0.data_out[0], out_i[0].in[0]);
		connect<pktstream>(nbody_inst1.data_out[0], out_i[1].in[0]);
		connect<pktstream>(nbody_inst2.data_out[0], out_i[2].in[0]);
		connect<pktstream>(nbody_inst3.data_out[0], out_i[3].in[0]);
		connect<pktstream>(nbody_inst4.data_out[0], out_i[4].in[0]);
		connect<pktstream>(nbody_inst5.data_out[0], out_i[5].in[0]);
		connect<pktstream>(nbody_inst6.data_out[0], out_i[6].in[0]);
		connect<pktstream>(nbody_inst7.data_out[0], out_i[7].in[0]);
		connect<pktstream>(nbody_inst8.data_out[0], out_i[8].in[0]);
		connect<pktstream>(nbody_inst9.data_out[0], out_i[9].in[0]);
		connect<pktstream>(nbody_inst10.data_out[0], out_i[10].in[0]);
		connect<pktstream>(nbody_inst11.data_out[0], out_i[11].in[0]);
		connect<pktstream>(nbody_inst12.data_out[0], out_i[12].in[0]);
		connect<pktstream>(nbody_inst13.data_out[0], out_i[13].in[0]);
		connect<pktstream>(nbody_inst14.data_out[0], out_i[14].in[0]);
		connect<pktstream>(nbody_inst15.data_out[0], out_i[15].in[0]);
		connect<pktstream>(nbody_inst16.data_out[0], out_i[16].in[0]);
		connect<pktstream>(nbody_inst17.data_out[0], out_i[17].in[0]);
		connect<pktstream>(nbody_inst18.data_out[0], out_i[18].in[0]);
		connect<pktstream>(nbody_inst19.data_out[0], out_i[19].in[0]);
		connect<pktstream>(nbody_inst20.data_out[0], out_i[20].in[0]);
		connect<pktstream>(nbody_inst21.data_out[0], out_i[21].in[0]);
		connect<pktstream>(nbody_inst22.data_out[0], out_i[22].in[0]);
		connect<pktstream>(nbody_inst23.data_out[0], out_i[23].in[0]);
		connect<pktstream>(nbody_inst24.data_out[0], out_i[24].in[0]);
		connect<pktstream>(nbody_inst25.data_out[0], out_i[25].in[0]);
		connect<pktstream>(nbody_inst26.data_out[0], out_i[26].in[0]);
		connect<pktstream>(nbody_inst27.data_out[0], out_i[27].in[0]);
		connect<pktstream>(nbody_inst28.data_out[0], out_i[28].in[0]);
		connect<pktstream>(nbody_inst29.data_out[0], out_i[29].in[0]);
		connect<pktstream>(nbody_inst30.data_out[0], out_i[30].in[0]);
		connect<pktstream>(nbody_inst31.data_out[0], out_i[31].in[0]);
		connect<pktstream>(nbody_inst32.data_out[0], out_i[32].in[0]);
		connect<pktstream>(nbody_inst33.data_out[0], out_i[33].in[0]);
		connect<pktstream>(nbody_inst34.data_out[0], out_i[34].in[0]);
		connect<pktstream>(nbody_inst35.data_out[0], out_i[35].in[0]);
		connect<pktstream>(nbody_inst36.data_out[0], out_i[36].in[0]);
		connect<pktstream>(nbody_inst37.data_out[0], out_i[37].in[0]);
		connect<pktstream>(nbody_inst38.data_out[0], out_i[38].in[0]);
		connect<pktstream>(nbody_inst39.data_out[0], out_i[39].in[0]);
		connect<pktstream>(nbody_inst40.data_out[0], out_i[40].in[0]);
		connect<pktstream>(nbody_inst41.data_out[0], out_i[41].in[0]);
		connect<pktstream>(nbody_inst42.data_out[0], out_i[42].in[0]);
		connect<pktstream>(nbody_inst43.data_out[0], out_i[43].in[0]);
		connect<pktstream>(nbody_inst44.data_out[0], out_i[44].in[0]);
		connect<pktstream>(nbody_inst45.data_out[0], out_i[45].in[0]);
		connect<pktstream>(nbody_inst46.data_out[0], out_i[46].in[0]);
		connect<pktstream>(nbody_inst47.data_out[0], out_i[47].in[0]);
		connect<pktstream>(nbody_inst48.data_out[0], out_i[48].in[0]);
		connect<pktstream>(nbody_inst49.data_out[0], out_i[49].in[0]);
		connect<pktstream>(nbody_inst50.data_out[0], out_i[50].in[0]);
		connect<pktstream>(nbody_inst51.data_out[0], out_i[51].in[0]);
		connect<pktstream>(nbody_inst52.data_out[0], out_i[52].in[0]);
		connect<pktstream>(nbody_inst53.data_out[0], out_i[53].in[0]);
		connect<pktstream>(nbody_inst54.data_out[0], out_i[54].in[0]);
		connect<pktstream>(nbody_inst55.data_out[0], out_i[55].in[0]);
		connect<pktstream>(nbody_inst56.data_out[0], out_i[56].in[0]);
		connect<pktstream>(nbody_inst57.data_out[0], out_i[57].in[0]);
		connect<pktstream>(nbody_inst58.data_out[0], out_i[58].in[0]);
		connect<pktstream>(nbody_inst59.data_out[0], out_i[59].in[0]);
		connect<pktstream>(nbody_inst60.data_out[0], out_i[60].in[0]);
		connect<pktstream>(nbody_inst61.data_out[0], out_i[61].in[0]);
		connect<pktstream>(nbody_inst62.data_out[0], out_i[62].in[0]);
		connect<pktstream>(nbody_inst63.data_out[0], out_i[63].in[0]);
		connect<pktstream>(nbody_inst64.data_out[0], out_i[64].in[0]);
		connect<pktstream>(nbody_inst65.data_out[0], out_i[65].in[0]);
		connect<pktstream>(nbody_inst66.data_out[0], out_i[66].in[0]);
		connect<pktstream>(nbody_inst67.data_out[0], out_i[67].in[0]);
		connect<pktstream>(nbody_inst68.data_out[0], out_i[68].in[0]);
		connect<pktstream>(nbody_inst69.data_out[0], out_i[69].in[0]);
		connect<pktstream>(nbody_inst70.data_out[0], out_i[70].in[0]);
		connect<pktstream>(nbody_inst71.data_out[0], out_i[71].in[0]);
		connect<pktstream>(nbody_inst72.data_out[0], out_i[72].in[0]);
		connect<pktstream>(nbody_inst73.data_out[0], out_i[73].in[0]);
		connect<pktstream>(nbody_inst74.data_out[0], out_i[74].in[0]);
		connect<pktstream>(nbody_inst75.data_out[0], out_i[75].in[0]);
		connect<pktstream>(nbody_inst76.data_out[0], out_i[76].in[0]);
		connect<pktstream>(nbody_inst77.data_out[0], out_i[77].in[0]);
		connect<pktstream>(nbody_inst78.data_out[0], out_i[78].in[0]);
		connect<pktstream>(nbody_inst79.data_out[0], out_i[79].in[0]);
		connect<pktstream>(nbody_inst80.data_out[0], out_i[80].in[0]);
		connect<pktstream>(nbody_inst81.data_out[0], out_i[81].in[0]);
		connect<pktstream>(nbody_inst82.data_out[0], out_i[82].in[0]);
		connect<pktstream>(nbody_inst83.data_out[0], out_i[83].in[0]);
		connect<pktstream>(nbody_inst84.data_out[0], out_i[84].in[0]);
		connect<pktstream>(nbody_inst85.data_out[0], out_i[85].in[0]);
		connect<pktstream>(nbody_inst86.data_out[0], out_i[86].in[0]);
		connect<pktstream>(nbody_inst87.data_out[0], out_i[87].in[0]);
		connect<pktstream>(nbody_inst88.data_out[0], out_i[88].in[0]);
		connect<pktstream>(nbody_inst89.data_out[0], out_i[89].in[0]);
		connect<pktstream>(nbody_inst90.data_out[0], out_i[90].in[0]);
		connect<pktstream>(nbody_inst91.data_out[0], out_i[91].in[0]);
		connect<pktstream>(nbody_inst92.data_out[0], out_i[92].in[0]);
		connect<pktstream>(nbody_inst93.data_out[0], out_i[93].in[0]);
		connect<pktstream>(nbody_inst94.data_out[0], out_i[94].in[0]);
		connect<pktstream>(nbody_inst95.data_out[0], out_i[95].in[0]);
		connect<pktstream>(nbody_inst96.data_out[0], out_i[96].in[0]);
		connect<pktstream>(nbody_inst97.data_out[0], out_i[97].in[0]);
		connect<pktstream>(nbody_inst98.data_out[0], out_i[98].in[0]);
		connect<pktstream>(nbody_inst99.data_out[0], out_i[99].in[0]);
 
	}
};
        
