#
# Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#

.PHONY: clean

clean:
	find . -type d -name "vfs_work" -exec rm -rf {} +
	find . -type d -name ".Xil" -exec rm -rf {} +
	find . -name "AIECompiler.log" -delete
