function v4acc = mac4_sym_v32(acc,xbuff,xstart,xoffsets,xstep,ystart,zbuff,zstart,zoffsets,zstep)

v4acc(1) = acc(1)+...
           zbuff(zstart+1+zoffsets(1))*        (xbuff(xstart+1+xoffsets(1))        +xbuff(ystart+1+xoffsets(1)))         + ...
           zbuff(zstart+1+zoffsets(1)+zstep)  *(xbuff(xstart+1+xoffsets(1)+xstep)  +xbuff(ystart+1+xoffsets(1)-xstep))   +...
           zbuff(zstart+1+zoffsets(1)+zstep*2)*(xbuff(xstart+1+xoffsets(1)+xstep*2)+xbuff(ystart+1+xoffsets(1)-xstep*2)) +...
           zbuff(zstart+1+zoffsets(1)+zstep*3)*(xbuff(xstart+1+xoffsets(1)+xstep*3)+xbuff(ystart+1+xoffsets(1)-xstep*3));
v4acc(2) = acc(2)+...
           zbuff(zstart+1+zoffsets(2))*        (xbuff(xstart+1+xoffsets(2))        +xbuff(ystart+1+xoffsets(2)))         + ...
           zbuff(zstart+1+zoffsets(2)+zstep)  *(xbuff(xstart+1+xoffsets(2)+xstep)  +xbuff(ystart+1+xoffsets(2)-xstep))   +...
           zbuff(zstart+1+zoffsets(2)+zstep*2)*(xbuff(xstart+1+xoffsets(2)+xstep*2)+xbuff(ystart+1+xoffsets(2)-xstep*2)) +...
           zbuff(zstart+1+zoffsets(2)+zstep*3)*(xbuff(xstart+1+xoffsets(2)+xstep*3)+xbuff(ystart+1+xoffsets(2)-xstep*3));
       
v4acc(3) = acc(3)+...
           zbuff(zstart+1+zoffsets(3))*        (xbuff(xstart+1+xoffsets(3))        +xbuff(ystart+1+xoffsets(3)))         + ...
           zbuff(zstart+1+zoffsets(3)+zstep)  *(xbuff(xstart+1+xoffsets(3)+xstep)  +xbuff(ystart+1+xoffsets(3)-xstep))   +...
           zbuff(zstart+1+zoffsets(3)+zstep*2)*(xbuff(xstart+1+xoffsets(3)+xstep*2)+xbuff(ystart+1+xoffsets(3)-xstep*2)) +...
           zbuff(zstart+1+zoffsets(3)+zstep*3)*(xbuff(xstart+1+xoffsets(3)+xstep*3)+xbuff(ystart+1+xoffsets(3)-xstep*3));

v4acc(4) = acc(4)+...
           zbuff(zstart+1+zoffsets(4))*        (xbuff(xstart+1+xoffsets(4))        +xbuff(ystart+1+xoffsets(4)))         + ...
           zbuff(zstart+1+zoffsets(4)+zstep)  *(xbuff(xstart+1+xoffsets(4)+xstep)  +xbuff(ystart+1+xoffsets(4)-xstep))   +...
           zbuff(zstart+1+zoffsets(4)+zstep*2)*(xbuff(xstart+1+xoffsets(4)+xstep*2)+xbuff(ystart+1+xoffsets(4)-xstep*2)) +...
           zbuff(zstart+1+zoffsets(4)+zstep*3)*(xbuff(xstart+1+xoffsets(4)+xstep*3)+xbuff(ystart+1+xoffsets(4)-xstep*3));
end

