function v8acc = mul4_sym_uct(xbuff,xstart,xoffsets,xstep,ystart,uct_col,uct_shift,zbuff,zstart,zoffsets,zstep)

v8acc(1) = zbuff(zstart+1+zoffsets(1))*        (xbuff(xstart+1+xoffsets(1))        +xbuff(ystart+1+xoffsets(1))) + ...
           zbuff(zstart+1+zoffsets(1)+zstep)*  (xbuff(xstart+1+xoffsets(1)+xstep)  +xbuff(ystart+1+xoffsets(1)-xstep)) + ...
           zbuff(zstart+1+zoffsets(1)+2*zstep)*(xbuff(xstart+1+xoffsets(1)+2*xstep)+xbuff(ystart+1+xoffsets(1)-2*xstep)) + ...
           zbuff(zstart+1+zoffsets(1)+3*zstep)*(xbuff(xstart+1+xoffsets(1)+3*xstep)+xbuff(ystart+1+xoffsets(1)-3*xstep));
v8acc(2) = zbuff(zstart+1+zoffsets(2))*        (xbuff(xstart+1+xoffsets(2))        +xbuff(ystart+1+xoffsets(2))) + ...
           zbuff(zstart+1+zoffsets(2)+zstep)*  (xbuff(xstart+1+xoffsets(2)+xstep)  +xbuff(ystart+1+xoffsets(2)-xstep)) + ...
           zbuff(zstart+1+zoffsets(2)+2*zstep)*(xbuff(xstart+1+xoffsets(2)+2*xstep)+xbuff(ystart+1+xoffsets(2)-2*xstep)) + ...
           zbuff(zstart+1+zoffsets(2)+3*zstep)*(xbuff(xstart+1+xoffsets(2)+3*xstep)+xbuff(ystart+1+xoffsets(2)-3*xstep));
v8acc(3) = zbuff(zstart+1+zoffsets(3))*        (xbuff(xstart+1+xoffsets(3))        +xbuff(ystart+1+xoffsets(3))) + ...
           zbuff(zstart+1+zoffsets(3)+zstep)*  (xbuff(xstart+1+xoffsets(3)+xstep)  +xbuff(ystart+1+xoffsets(3)-xstep)) + ...
           zbuff(zstart+1+zoffsets(3)+2*zstep)*(xbuff(xstart+1+xoffsets(3)+2*xstep)+xbuff(ystart+1+xoffsets(3)-2*xstep)) + ...
           zbuff(zstart+1+zoffsets(3)+3*zstep)*(xbuff(xstart+1+xoffsets(3)+3*xstep)+xbuff(ystart+1+xoffsets(3)-3*xstep));
v8acc(4) = zbuff(zstart+1+zoffsets(4))*        (xbuff(xstart+1+xoffsets(4))        +xbuff(ystart+1+xoffsets(4))) + ...
           zbuff(zstart+1+zoffsets(4)+zstep)*  (xbuff(xstart+1+xoffsets(4)+xstep)  +xbuff(ystart+1+xoffsets(4)-xstep)) + ...
           zbuff(zstart+1+zoffsets(4)+2*zstep)*(xbuff(xstart+1+xoffsets(4)+2*xstep)+xbuff(ystart+1+xoffsets(4)-2*xstep)) + ...
           zbuff(zstart+1+zoffsets(4)+3*zstep)*(xbuff(xstart+1+xoffsets(4)+3*xstep)+xbuff(ystart+1+xoffsets(4)-3*xstep));

v8acc(5) = xbuff(ystart+1+xoffsets(1)-xstep*uct_col)*2^uct_shift;
v8acc(6) = xbuff(ystart+1+xoffsets(2)-xstep*uct_col)*2^uct_shift;
v8acc(7) = xbuff(ystart+1+xoffsets(3)-xstep*uct_col)*2^uct_shift;
v8acc(8) = xbuff(ystart+1+xoffsets(4)-xstep*uct_col)*2^uct_shift;

end
