%
% Copyright 2021-2022 Xilinx, Inc.
%
% Licensed under the Apache License, Version 2.0 (the "License");
% you may not use this file except in compliance with the License.
% You may obtain a copy of the License at
%
%     http://www.apache.org/licenses/LICENSE-2.0
%
% Unless required by applicable law or agreed to in writing, software
% distributed under the License is distributed on an "AS IS" BASIS,
% WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
% See the License for the specific language governing permissions and
% limitations under the License.
%

function Hd = ChannelFilter
%CHANNELFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 23-Nov-2020 15:27:15

% FIR Window Raised-cosine filter designed using the FIRRCOS function.

% All frequency values are normalized to 1.

N    = 120;        % Order
Fc   = 0.8;        % Cutoff Frequency
TM   = 'Rolloff';  % Transition Mode
R    = 0.25;       % Rolloff
DT   = 'sqrt';     % Design Type
Beta = 1;          % Window Parameter

% Create the window vector for the design algorithm.
win = kaiser(N+1, Beta);

% Calculate the coefficients using the FIR1 function.
b  = firrcos(N, Fc, R, 2, TM, DT, [], win);
Hd = dfilt.dffir(b);

% [EOF]
