#####################################################################
# Copyright © 2025 Advanced Micro Devices, Inc. All rights reserved.
# SPDX-License-Identifier: MIT
#####################################################################

all:
	g++ -Wall -mavx -o vadd_avx vadd_avx.cpp
	./vadd_avx

clean:
	rm -rf vadd_avx 
