#/*
#Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
#SPDX-License-Identifier: MIT
#*/

############################## Setting up Project Variables ##############################
TARGET := hw_emu
SYSROOT := $(EDGE_COMMON_SW)/sysroots/cortexa72-cortexa53-amd-linux
SD_IMAGE_FILE := $(EDGE_COMMON_SW)/Image

EMU_PS := QEMU
ifeq ($(TARGET), sw_emu)
EMU_PS := X86
endif

ifeq ($(EMU_PS),X86)
CXX := g++
else
CXX := $(XILINX_VITIS)/gnu/aarch64/lin/aarch64-linux/bin/aarch64-linux-gnu-g++
endif

#Check for EMU_PS
ifeq ($(TARGET), $(filter $(TARGET),hw_emu hw))
ifeq ($(EMU_PS), X86)
$(error For hw_emu and hw, the design has to run on QEMU. Thus, please give EMU_PS=QEMU for these targets.)
endif
endif

# Makefile input options
LINK_OUTPUT := aieml.xsa
XCLBIN := krnl_aieml.xclbin
AIE_DATA= ./aie_src/data


# File names and locations
GRAPH := ./aie_src/src/graph.cpp
GRAPH_O := libadf.a

KERNEL := pl_src/s2mm_16_128.cpp pl_src/mm2s_8_128.cpp pl_src/s2mm_32_128.cpp
KERNEL_XO := pl_src/s2mm_16_128.xo pl_src/mm2s_8_128.xo pl_src/s2mm_32_128.xo

HOST_SRCS := ./host/host.cpp
EXECUTABLE = ./aieml_system

# SoC variables
RUN_APP_SCRIPT = run_aieml.sh
PACKAGE_OUT = ./package.$(TARGET)

LAUNCH_EMULATOR = $(PACKAGE_OUT)/launch_$(TARGET).sh
RESULT_STRING = TEST PASSED


CONFIG_FILE := system.cfg


# Command-line options
VPP := v++
AIECC := aiecompiler
AIESIM := aiesimulator

AIE_INCLUDE_FLAGS := -include="$(XILINX_VITIS)/aietools/include" -include="./aie_src/src/" -include="./aie_src/data" -include="./"
AIE_FLAGS := --platform $(PLATFORM) $(AIE_INCLUDE_FLAGS) --pl-freq=100 -workdir=./Work

ifeq ($(TARGET),sw_emu)
	AIE_FLAGS += --target=x86sim -Xpreproc='-DNDEBUG'       
else
	AIE_FLAGS += --target=hw
endif

VPP_XO_FLAGS := -c -t $(TARGET) --platform $(PLATFORM) --save-temps -g 
VPP_LINK_FLAGS := -l --platform $(PLATFORM) $(KERNEL_XO) $(GRAPH_O) -t $(TARGET) --save-temps -g --config $(CONFIG_FILE) -o $(LINK_OUTPUT)

GCC_FLAGS := -Wall -c \
			 -std=c++17 \
			 -Wno-int-to-pointer-cast \
			 --sysroot=$(SYSROOT) \

GCC_INCLUDES := -I$(SYSROOT)/usr/include/xrt \
				-I$(SYSROOT)/usr/include \
				-I./ -I./src/ \
				-I${XILINX_VITIS}/aietools/include \
				-I${XILINX_VITIS}/include


GCC_LIB := -lxrt_core -lxrt_coreutil \
		   -L$(SYSROOT)/usr/lib \
		   --sysroot=$(SYSROOT) \
		   -L${XILINX_VITIS}/aietools/lib/aarch64.o

ifeq ($(TARGET),$(filter $(TARGET),sw_emu))
ifeq ($(EMU_PS), X86)
       GCC_LIB := -lxrt_coreutil -L${XILINX_VITIS}/aietools/lib/lnx64.o -L${XILINX_XRT}/lib
       GCC_FLAGS := -Wall -c -std=c++17 -Wno-int-to-pointer-cast -I${XILINX_XRT}/include
       GCC_INCLUDES := -I./src/ -I./ -I${XILINX_VITIS}/aietools/include
else
       GCC_LIB := -lxrt_coreutil -L$(SYSROOT)/usr/lib --sysroot=$(SYSROOT) -L${XILINX_VITIS}/aietools/lib/aarch64.o
endif
endif

.PHONY: all clean cleanall docs emconfig
ifeq ($(EMU_PS), X86)
all:  kernels graph build host emconfig sd_card
else
all:   kernels graph build host emconfig sd_card
endif

emconfig:
	emconfigutil --platform $(PLATFORM) --od .

######################################################
# This step compiles the HLS C kernels and creates an ADF Graph
# the %.xo is used as the output and creates from the %.cpp files
# The graph is generated by having the -target=hw
kernels: $(KERNEL_XO)
	@echo "COMPLETE: Kernels Created."	

pl_src/s2mm_16_128.xo: pl_src/s2mm_16_128.cpp
	$(VPP) $(VPP_XO_FLAGS) -k $(basename $(notdir $<)) $< -o $@
pl_src/mm2s_8_128.xo: pl_src/mm2s_8_128.cpp
	$(VPP) $(VPP_XO_FLAGS) -k $(basename $(notdir $<)) $< -o $@
pl_src/s2mm_32_128.xo: pl_src/s2mm_32_128.cpp
	$(VPP) $(VPP_XO_FLAGS) -k $(basename $(notdir $<)) $< -o $@


graph:  $(GRAPH_O)

aiesim: $(GRAPH_O)
	$(AIESIM) --pkg-dir=./Work 

$(GRAPH_O): $(GRAPH)
	$(AIECC) $(AIE_FLAGS) $(GRAPH)
	@echo "COMPLETE: libadf.a created."      
#####################################################

########################################################
# Once the kernels and graph are generated, you can build
# the hardware part of the design. This creates an xclbin
# that will be used to run the design on the platform.
build:  $(LINK_OUTPUT)

$(LINK_OUTPUT): $(KERNEL_XO) $(GRAPH_O) 
	$(VPP) $(VPP_LINK_FLAGS) || (echo "task: [xclbin] failed error code: $$?"; exit 1)       
	@echo "COMPLETE:.xsa created"
########################################################

############################################################################################################################
# For hardware and hardware emulation, compile the PS code and generate the aieml_system executable. This is needed for creating the sd_card.
host: $(EXECUTABLE)

$(EXECUTABLE): $(HOST_SRCS) 
ifneq ($(EMU_PS), X86)
endif 
		$(CXX) $(HOST_SRCS) $(GCC_FLAGS) $(GCC_INCLUDES) -o main.o
		$(CXX) *.o $(GCC_LIB) -o $(EXECUTABLE)
	@echo "COMPLETE: Host application created."
############################################################################################################################

##################################################################################################
# Depending on the TARGET, it'll either generate the PDI for hw_emu or hw.
sd_card:  $(LINK_OUTPUT) $(XCLBIN)	

$(XCLBIN): $(GRAPH_O) $(KERNEL_XO) $(EXECUTABLE)
ifeq ($(TARGET),$(filter $(TARGET),sw_emu hw_emu))
ifeq ($(EMU_PS), X86)
	v++ $(VPP_PFLAGS) -p -t $(TARGET) \
                 --package.defer_aie_run \
                 --platform $(PLATFORM) \
                 --package.out_dir $(PACKAGE_OUT) \
                 $(LINK_OUTPUT) $(GRAPH_O) -o $(XCLBIN)
else
	v++ $(VPP_PFLAGS) -p -t $(TARGET) \
		--platform $(PLATFORM) \
		--package.out_dir $(PACKAGE_OUT) \
		--package.rootfs $(EDGE_COMMON_SW)/rootfs.ext4 \
		--package.image_format=ext4 \
		--package.boot_mode=sd \
		--package.kernel_image $(SD_IMAGE_FILE) \
		--package.defer_aie_run \
		--package.sd_file ../$(RUN_APP_SCRIPT) \
		--package.sd_file $(AIE_DATA) \
		--package.sd_file aieml_system $(LINK_OUTPUT) $(GRAPH_O) -o $(XCLBIN)
	@echo "COMPLETE: emulation package created."
endif
else
	v++ $(VPP_PFLAGS) -p -t hw \
		--platform $(PLATFORM) \
		--package.out_dir $(PACKAGE_OUT) \
		--package.rootfs $(EDGE_COMMON_SW)/rootfs.ext4 \
		--package.image_format=ext4 \
		--package.boot_mode=sd \
		--package.kernel_image=$(SD_IMAGE_FILE) \
		--package.defer_aie_run \
		--package.sd_file ../$(RUN_APP_SCRIPT) \
		--package.sd_file $(AIE_DATA) \
		--package.sd_file aieml_system $(LINK_OUTPUT) $(GRAPH_O) -o $(XCLBIN)

	@echo "COMPLETE: hw package created."
endif

###################################################################################################

###########################################################################
# If the target is for HW_EMU, launch the emulator

run: all 
ifeq ($(TARGET),$(filter $(TARGET),sw_emu hw_emu))
ifeq ($(EMU_PS), X86)
	XCL_EMULATION_MODE=$(TARGET) $(EXECUTABLE) $(CMD_ARGS)
else
	bash -c '$(LAUNCH_EMULATOR) -run-app $(RUN_APP_SCRIPT) | tee run_app.log; exit $${PIPESTATUS[0]}'
endif
else
	@echo "Hardware build, no emulation executed."
endif

test: $(EXECUTABLE)
ifeq ($(TARGET),$(filter $(TARGET),sw_emu hw_emu))
ifeq ($(EMU_PS), X86)
	XCL_EMULATION_MODE=$(TARGET) $(EXECUTABLE) $(CMD_ARGS)
else
	bash -c '$(LAUNCH_EMULATOR) -run-app $(RUN_APP_SCRIPT) | tee run_app.log; exit $${PIPESTATUS[0]}'
endif
else
	@echo "Hardware build, no emulation executed."
endif

check_edge_sw:
ifndef EDGE_COMMON_SW
	$(error EDGE_COMMON_SW variable is not set, please download and use the pre-built image from https://www.xilinx.com/support/download/index.html/content/xilinx/en/downloadNav/embedded-platforms.html)
endif

############################## Cleaning Rules ##############################
# Cleaning stuff
clean:
	rm -rf $(EXECUTABLE) $(XCLBIN)  *.log  *.xsa *.xclbin
	rm -rf profile_* TempConfig system_estimate.xtxt *.rpt *.csv *.o *.xo *.xpe *.xsa cfg qemu_dts_files emu_qemu_scripts *.db sim *.sh *.a 
	rm -rf /src/sw/*.ll /src/pl_kernels/*.ll src/aie/*.ll *v++* .Xil emconfig.json dltmp* xmltmp* *.log *.jou *.wcfg *.wdb *bin* *summary* *.BIN *.bif *.exe Work *.log *.txt 

ultraclean: clean
	-rm -rf build_dir* sd_card*
	-rm -rf package.* 
	-rm -rf _x* *xclbin.run_summary qemu-memory-_* emulation _vimage start_simulation.sh *.xclbin

