build: 

	vitis -s project.py

.PHONY: run
run: build
	@echo "Finished build and run"

check:
	@echo "Finished check"

all: run


# -----------------------------------------------------------------------------
#
clean:
	rm -rf myProject
#
