// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="polar_clip_polar_clip,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=3.200000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.242000,HLS_SYN_LAT=22,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=375,HLS_SYN_LUT=1008,HLS_VERSION=2022_1}" *)

module polar_clip (
        ap_clk,
        ap_rst_n,
        in_sample_TDATA,
        in_sample_TVALID,
        in_sample_TREADY,
        in_sample_TKEEP,
        in_sample_TSTRB,
        in_sample_TLAST,
        out_sample_TDATA,
        out_sample_TVALID,
        out_sample_TREADY,
        out_sample_TKEEP,
        out_sample_TSTRB,
        out_sample_TLAST
);

parameter    ap_ST_fsm_state1 = 11'd1;
parameter    ap_ST_fsm_state2 = 11'd2;
parameter    ap_ST_fsm_state3 = 11'd4;
parameter    ap_ST_fsm_state4 = 11'd8;
parameter    ap_ST_fsm_state5 = 11'd16;
parameter    ap_ST_fsm_state6 = 11'd32;
parameter    ap_ST_fsm_state7 = 11'd64;
parameter    ap_ST_fsm_state8 = 11'd128;
parameter    ap_ST_fsm_state9 = 11'd256;
parameter    ap_ST_fsm_state10 = 11'd512;
parameter    ap_ST_fsm_state11 = 11'd1024;

input   ap_clk;
input   ap_rst_n;
input  [31:0] in_sample_TDATA;
input   in_sample_TVALID;
output   in_sample_TREADY;
input  [3:0] in_sample_TKEEP;
input  [3:0] in_sample_TSTRB;
input  [0:0] in_sample_TLAST;
output  [31:0] out_sample_TDATA;
output   out_sample_TVALID;
input   out_sample_TREADY;
output  [3:0] out_sample_TKEEP;
output  [3:0] out_sample_TSTRB;
output  [0:0] out_sample_TLAST;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [5:0] rotation_sin_lut_address0;
reg    rotation_sin_lut_ce0;
wire   [15:0] rotation_sin_lut_q0;
wire   [5:0] rotation_cos_lut_address0;
reg    rotation_cos_lut_ce0;
wire   [15:0] rotation_cos_lut_q0;
reg    in_sample_TDATA_blk_n;
(* fsm_encoding = "none" *) reg   [10:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    out_sample_TDATA_blk_n;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire  signed [15:0] value_real_fu_163_p1;
reg  signed [15:0] value_real_reg_435;
wire  signed [31:0] sext_ln158_fu_181_p1;
wire   [0:0] tmp_fu_189_p3;
reg   [0:0] tmp_reg_446;
wire  signed [16:0] abs_I_V_1_fu_203_p3;
reg  signed [16:0] abs_I_V_1_reg_452;
wire   [0:0] tmp_1_fu_211_p3;
reg   [0:0] tmp_1_reg_458;
wire  signed [16:0] abs_Q_V_1_fu_225_p3;
reg  signed [16:0] abs_Q_V_1_reg_464;
wire  signed [31:0] sext_ln157_fu_233_p1;
wire    ap_CS_fsm_state2;
wire   [17:0] X_step_V_fu_242_p2;
reg   [17:0] X_step_V_reg_476;
wire   [0:0] xor_ln1085_fu_253_p2;
reg   [0:0] xor_ln1085_reg_481;
wire   [17:0] Y_step_V_4_fu_271_p3;
reg   [17:0] Y_step_V_4_reg_487;
wire  signed [31:0] grp_fu_387_p2;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln1081_fu_283_p2;
reg   [0:0] icmp_ln1081_reg_500;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
(* use_dsp48 = "no" *) wire  signed [15:0] add_ln75_fu_360_p2;
wire    grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start;
wire    grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_done;
wire    grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_idle;
wire    grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_ready;
wire   [5:0] grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_rotation_index_V_out;
wire    grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_rotation_index_V_out_ap_vld;
wire   [24:0] grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_X_step_V_1_out;
wire    grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_X_step_V_1_out_ap_vld;
reg    grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [5:0] rotation_index_V_loc_fu_90;
reg  signed [24:0] X_step_V_1_loc_fu_86;
wire   [63:0] zext_ln587_fu_291_p1;
wire  signed [15:0] value_imag_fu_167_p4;
wire  signed [16:0] sext_ln157_1_fu_177_p1;
wire   [16:0] abs_I_V_fu_197_p2;
wire  signed [16:0] sext_ln158_1_fu_185_p1;
wire   [16:0] abs_Q_V_fu_219_p2;
wire  signed [17:0] sext_ln41_1_fu_239_p1;
wire  signed [17:0] sext_ln41_fu_236_p1;
wire   [0:0] icmp_ln1085_fu_249_p2;
wire   [17:0] Y_step_V_fu_259_p2;
wire   [17:0] Y_step_V_3_fu_265_p2;
wire  signed [31:0] grp_fu_393_p3;
wire   [15:0] sub_ln75_fu_297_p2;
wire   [15:0] sub_ln75_1_fu_310_p2;
wire   [15:0] select_ln90_fu_303_p3;
wire   [15:0] select_ln101_fu_323_p3;
wire   [15:0] select_ln95_fu_316_p3;
wire   [15:0] select_ln106_fu_330_p3;
wire  signed [24:0] grp_fu_402_p2;
wire   [15:0] trunc_ln_fu_351_p4;
wire  signed [15:0] grp_fu_409_p2;
wire  signed [15:0] grp_fu_416_p2;
wire   [15:0] ovalue_imag_V_1_fu_372_p3;
wire   [15:0] ovalue_real_V_1_fu_366_p3;
wire  signed [15:0] grp_fu_387_p0;
wire  signed [15:0] grp_fu_387_p1;
wire  signed [15:0] grp_fu_393_p0;
wire  signed [15:0] grp_fu_393_p1;
wire   [8:0] grp_fu_402_p1;
wire  signed [15:0] grp_fu_409_p1;
wire  signed [15:0] grp_fu_416_p1;
reg    grp_fu_387_ce;
reg    grp_fu_393_ce;
reg    grp_fu_409_ce;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
reg    grp_fu_416_ce;
reg   [10:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
reg    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
wire    regslice_both_out_sample_V_data_V_U_apdone_blk;
reg    ap_block_state11;
wire    regslice_both_in_sample_V_data_V_U_apdone_blk;
wire   [31:0] in_sample_TDATA_int_regslice;
wire    in_sample_TVALID_int_regslice;
reg    in_sample_TREADY_int_regslice;
wire    regslice_both_in_sample_V_data_V_U_ack_in;
wire    regslice_both_in_sample_V_keep_V_U_apdone_blk;
wire   [3:0] in_sample_TKEEP_int_regslice;
wire    regslice_both_in_sample_V_keep_V_U_vld_out;
wire    regslice_both_in_sample_V_keep_V_U_ack_in;
wire    regslice_both_in_sample_V_strb_V_U_apdone_blk;
wire   [3:0] in_sample_TSTRB_int_regslice;
wire    regslice_both_in_sample_V_strb_V_U_vld_out;
wire    regslice_both_in_sample_V_strb_V_U_ack_in;
wire    regslice_both_in_sample_V_last_V_U_apdone_blk;
wire   [0:0] in_sample_TLAST_int_regslice;
wire    regslice_both_in_sample_V_last_V_U_vld_out;
wire    regslice_both_in_sample_V_last_V_U_ack_in;
wire   [31:0] out_sample_TDATA_int_regslice;
reg    out_sample_TVALID_int_regslice;
wire    out_sample_TREADY_int_regslice;
wire    regslice_both_out_sample_V_data_V_U_vld_out;
wire    regslice_both_out_sample_V_keep_V_U_apdone_blk;
wire    regslice_both_out_sample_V_keep_V_U_ack_in_dummy;
wire    regslice_both_out_sample_V_keep_V_U_vld_out;
wire    regslice_both_out_sample_V_strb_V_U_apdone_blk;
wire    regslice_both_out_sample_V_strb_V_U_ack_in_dummy;
wire    regslice_both_out_sample_V_strb_V_U_vld_out;
wire    regslice_both_out_sample_V_last_V_U_apdone_blk;
wire    regslice_both_out_sample_V_last_V_U_ack_in_dummy;
wire    regslice_both_out_sample_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 11'd1;
#0 grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start_reg = 1'b0;
end

polar_clip_rotation_sin_lut_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
rotation_sin_lut_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rotation_sin_lut_address0),
    .ce0(rotation_sin_lut_ce0),
    .q0(rotation_sin_lut_q0)
);

polar_clip_rotation_cos_lut_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
rotation_cos_lut_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(rotation_cos_lut_address0),
    .ce0(rotation_cos_lut_ce0),
    .q0(rotation_cos_lut_q0)
);

polar_clip_polar_clip_Pipeline_VITIS_LOOP_71_1 grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start),
    .ap_done(grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_done),
    .ap_idle(grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_idle),
    .ap_ready(grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_ready),
    .sext_ln41_3(Y_step_V_4_reg_487),
    .sext_ln41_2(X_step_V_reg_476),
    .rotation_index_V_out(grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_rotation_index_V_out),
    .rotation_index_V_out_ap_vld(grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_rotation_index_V_out_ap_vld),
    .X_step_V_1_out(grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_X_step_V_1_out),
    .X_step_V_1_out_ap_vld(grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_X_step_V_1_out_ap_vld)
);

polar_clip_mul_mul_16s_16s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
mul_mul_16s_16s_32_4_1_U5(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_387_p0),
    .din1(grp_fu_387_p1),
    .ce(grp_fu_387_ce),
    .dout(grp_fu_387_p2)
);

polar_clip_mac_muladd_16s_16s_32s_32_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
mac_muladd_16s_16s_32s_32_4_1_U6(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_393_p0),
    .din1(grp_fu_393_p1),
    .din2(grp_fu_387_p2),
    .ce(grp_fu_393_ce),
    .dout(grp_fu_393_p3)
);

polar_clip_mul_mul_25s_9ns_25_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 25 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_mul_25s_9ns_25_4_1_U7(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(X_step_V_1_loc_fu_86),
    .din1(grp_fu_402_p1),
    .ce(1'b1),
    .dout(grp_fu_402_p2)
);

polar_clip_mul_mul_16s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_mul_16s_16s_16_4_1_U8(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(add_ln75_fu_360_p2),
    .din1(grp_fu_409_p1),
    .ce(grp_fu_409_ce),
    .dout(grp_fu_409_p2)
);

polar_clip_mul_mul_16s_16s_16_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mul_mul_16s_16s_16_4_1_U9(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(add_ln75_fu_360_p2),
    .din1(grp_fu_416_p1),
    .ce(grp_fu_416_ce),
    .dout(grp_fu_416_p2)
);

polar_clip_regslice_both #(
    .DataWidth( 32 ))
regslice_both_in_sample_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_sample_TDATA),
    .vld_in(in_sample_TVALID),
    .ack_in(regslice_both_in_sample_V_data_V_U_ack_in),
    .data_out(in_sample_TDATA_int_regslice),
    .vld_out(in_sample_TVALID_int_regslice),
    .ack_out(in_sample_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_sample_V_data_V_U_apdone_blk)
);

polar_clip_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_sample_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_sample_TKEEP),
    .vld_in(in_sample_TVALID),
    .ack_in(regslice_both_in_sample_V_keep_V_U_ack_in),
    .data_out(in_sample_TKEEP_int_regslice),
    .vld_out(regslice_both_in_sample_V_keep_V_U_vld_out),
    .ack_out(in_sample_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_sample_V_keep_V_U_apdone_blk)
);

polar_clip_regslice_both #(
    .DataWidth( 4 ))
regslice_both_in_sample_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_sample_TSTRB),
    .vld_in(in_sample_TVALID),
    .ack_in(regslice_both_in_sample_V_strb_V_U_ack_in),
    .data_out(in_sample_TSTRB_int_regslice),
    .vld_out(regslice_both_in_sample_V_strb_V_U_vld_out),
    .ack_out(in_sample_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_sample_V_strb_V_U_apdone_blk)
);

polar_clip_regslice_both #(
    .DataWidth( 1 ))
regslice_both_in_sample_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in_sample_TLAST),
    .vld_in(in_sample_TVALID),
    .ack_in(regslice_both_in_sample_V_last_V_U_ack_in),
    .data_out(in_sample_TLAST_int_regslice),
    .vld_out(regslice_both_in_sample_V_last_V_U_vld_out),
    .ack_out(in_sample_TREADY_int_regslice),
    .apdone_blk(regslice_both_in_sample_V_last_V_U_apdone_blk)
);

polar_clip_regslice_both #(
    .DataWidth( 32 ))
regslice_both_out_sample_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_sample_TDATA_int_regslice),
    .vld_in(out_sample_TVALID_int_regslice),
    .ack_in(out_sample_TREADY_int_regslice),
    .data_out(out_sample_TDATA),
    .vld_out(regslice_both_out_sample_V_data_V_U_vld_out),
    .ack_out(out_sample_TREADY),
    .apdone_blk(regslice_both_out_sample_V_data_V_U_apdone_blk)
);

polar_clip_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_sample_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd0),
    .vld_in(out_sample_TVALID_int_regslice),
    .ack_in(regslice_both_out_sample_V_keep_V_U_ack_in_dummy),
    .data_out(out_sample_TKEEP),
    .vld_out(regslice_both_out_sample_V_keep_V_U_vld_out),
    .ack_out(out_sample_TREADY),
    .apdone_blk(regslice_both_out_sample_V_keep_V_U_apdone_blk)
);

polar_clip_regslice_both #(
    .DataWidth( 4 ))
regslice_both_out_sample_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd0),
    .vld_in(out_sample_TVALID_int_regslice),
    .ack_in(regslice_both_out_sample_V_strb_V_U_ack_in_dummy),
    .data_out(out_sample_TSTRB),
    .vld_out(regslice_both_out_sample_V_strb_V_U_vld_out),
    .ack_out(out_sample_TREADY),
    .apdone_blk(regslice_both_out_sample_V_strb_V_U_apdone_blk)
);

polar_clip_regslice_both #(
    .DataWidth( 1 ))
regslice_both_out_sample_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(out_sample_TVALID_int_regslice),
    .ack_in(regslice_both_out_sample_V_last_V_U_ack_in_dummy),
    .data_out(out_sample_TLAST),
    .vld_out(regslice_both_out_sample_V_last_V_U_vld_out),
    .ack_out(out_sample_TREADY),
    .apdone_blk(regslice_both_out_sample_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state2)) begin
            grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start_reg <= 1'b1;
        end else if ((grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_ready == 1'b1)) begin
            grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_X_step_V_1_out_ap_vld == 1'b1))) begin
        X_step_V_1_loc_fu_86 <= grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_X_step_V_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        X_step_V_reg_476 <= X_step_V_fu_242_p2;
        Y_step_V_4_reg_487 <= Y_step_V_4_fu_271_p3;
        xor_ln1085_reg_481 <= xor_ln1085_fu_253_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        abs_I_V_1_reg_452 <= abs_I_V_1_fu_203_p3;
        abs_Q_V_1_reg_464 <= abs_Q_V_1_fu_225_p3;
        tmp_1_reg_458 <= in_sample_TDATA_int_regslice[32'd31];
        tmp_reg_446 <= in_sample_TDATA_int_regslice[32'd15];
        value_real_reg_435 <= value_real_fu_163_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        icmp_ln1081_reg_500 <= icmp_ln1081_fu_283_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state3) & (grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_rotation_index_V_out_ap_vld == 1'b1))) begin
        rotation_index_V_loc_fu_90 <= grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_rotation_index_V_out;
    end
end

always @ (*) begin
    if ((out_sample_TREADY_int_regslice == 1'b0)) begin
        ap_ST_fsm_state10_blk = 1'b1;
    end else begin
        ap_ST_fsm_state10_blk = 1'b0;
    end
end

always @ (*) begin
    if (((out_sample_TREADY_int_regslice == 1'b0) | (regslice_both_out_sample_V_data_V_U_apdone_blk == 1'b1))) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((in_sample_TVALID_int_regslice == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | ((in_sample_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1)) | ((1'b1 == ap_CS_fsm_state3) & (grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_done == 1'b1)))) begin
        grp_fu_387_ce = 1'b1;
    end else begin
        grp_fu_387_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state3) & (grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_done == 1'b1)))) begin
        grp_fu_393_ce = 1'b1;
    end else begin
        grp_fu_393_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | ((out_sample_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_fu_409_ce = 1'b1;
    end else begin
        grp_fu_409_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | ((out_sample_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state10)))) begin
        grp_fu_416_ce = 1'b1;
    end else begin
        grp_fu_416_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        in_sample_TDATA_blk_n = in_sample_TVALID_int_regslice;
    end else begin
        in_sample_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((in_sample_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        in_sample_TREADY_int_regslice = 1'b1;
    end else begin
        in_sample_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        out_sample_TDATA_blk_n = out_sample_TREADY_int_regslice;
    end else begin
        out_sample_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((out_sample_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
        out_sample_TVALID_int_regslice = 1'b1;
    end else begin
        out_sample_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rotation_cos_lut_ce0 = 1'b1;
    end else begin
        rotation_cos_lut_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        rotation_sin_lut_ce0 = 1'b1;
    end else begin
        rotation_sin_lut_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((in_sample_TVALID_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((1'b1 == ap_CS_fsm_state3) & (grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            if (((out_sample_TREADY_int_regslice == 1'b1) & (1'b1 == ap_CS_fsm_state10))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state11 : begin
            if ((~((out_sample_TREADY_int_regslice == 1'b0) | (regslice_both_out_sample_V_data_V_U_apdone_blk == 1'b1)) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign X_step_V_fu_242_p2 = ($signed(sext_ln41_1_fu_239_p1) + $signed(sext_ln41_fu_236_p1));

assign Y_step_V_3_fu_265_p2 = ($signed(sext_ln41_1_fu_239_p1) - $signed(sext_ln41_fu_236_p1));

assign Y_step_V_4_fu_271_p3 = ((xor_ln1085_fu_253_p2[0:0] == 1'b1) ? Y_step_V_fu_259_p2 : Y_step_V_3_fu_265_p2);

assign Y_step_V_fu_259_p2 = ($signed(sext_ln41_fu_236_p1) - $signed(sext_ln41_1_fu_239_p1));

assign abs_I_V_1_fu_203_p3 = ((tmp_fu_189_p3[0:0] == 1'b1) ? abs_I_V_fu_197_p2 : sext_ln157_1_fu_177_p1);

assign abs_I_V_fu_197_p2 = ($signed(17'd0) - $signed(sext_ln157_1_fu_177_p1));

assign abs_Q_V_1_fu_225_p3 = ((tmp_1_fu_211_p3[0:0] == 1'b1) ? abs_Q_V_fu_219_p2 : sext_ln158_1_fu_185_p1);

assign abs_Q_V_fu_219_p2 = ($signed(17'd0) - $signed(sext_ln158_1_fu_185_p1));

assign add_ln75_fu_360_p2 = ($signed(trunc_ln_fu_351_p4) + $signed(16'd53910));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11 = ((out_sample_TREADY_int_regslice == 1'b0) | (regslice_both_out_sample_V_data_V_U_apdone_blk == 1'b1));
end

assign grp_fu_387_p0 = sext_ln158_fu_181_p1;

assign grp_fu_387_p1 = sext_ln158_fu_181_p1;

assign grp_fu_393_p0 = sext_ln157_fu_233_p1;

assign grp_fu_393_p1 = sext_ln157_fu_233_p1;

assign grp_fu_402_p1 = 25'd311;

assign grp_fu_409_p1 = ((xor_ln1085_reg_481[0:0] == 1'b1) ? select_ln90_fu_303_p3 : select_ln101_fu_323_p3);

assign grp_fu_416_p1 = ((xor_ln1085_reg_481[0:0] == 1'b1) ? select_ln95_fu_316_p3 : select_ln106_fu_330_p3);

assign grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start = grp_polar_clip_Pipeline_VITIS_LOOP_71_1_fu_151_ap_start_reg;

assign icmp_ln1081_fu_283_p2 = (($signed(grp_fu_393_p3) > $signed(32'd135163876)) ? 1'b1 : 1'b0);

assign icmp_ln1085_fu_249_p2 = (($signed(abs_Q_V_1_reg_464) < $signed(abs_I_V_1_reg_452)) ? 1'b1 : 1'b0);

assign in_sample_TREADY = regslice_both_in_sample_V_data_V_U_ack_in;

assign out_sample_TDATA_int_regslice = {{ovalue_imag_V_1_fu_372_p3}, {ovalue_real_V_1_fu_366_p3}};

assign out_sample_TVALID = regslice_both_out_sample_V_data_V_U_vld_out;

assign ovalue_imag_V_1_fu_372_p3 = ((icmp_ln1081_reg_500[0:0] == 1'b1) ? grp_fu_416_p2 : 16'd0);

assign ovalue_real_V_1_fu_366_p3 = ((icmp_ln1081_reg_500[0:0] == 1'b1) ? grp_fu_409_p2 : 16'd0);

assign rotation_cos_lut_address0 = zext_ln587_fu_291_p1;

assign rotation_sin_lut_address0 = zext_ln587_fu_291_p1;

assign select_ln101_fu_323_p3 = ((tmp_reg_446[0:0] == 1'b1) ? sub_ln75_1_fu_310_p2 : rotation_cos_lut_q0);

assign select_ln106_fu_330_p3 = ((tmp_1_reg_458[0:0] == 1'b1) ? sub_ln75_fu_297_p2 : rotation_sin_lut_q0);

assign select_ln90_fu_303_p3 = ((tmp_reg_446[0:0] == 1'b1) ? sub_ln75_fu_297_p2 : rotation_sin_lut_q0);

assign select_ln95_fu_316_p3 = ((tmp_1_reg_458[0:0] == 1'b1) ? sub_ln75_1_fu_310_p2 : rotation_cos_lut_q0);

assign sext_ln157_1_fu_177_p1 = value_real_fu_163_p1;

assign sext_ln157_fu_233_p1 = value_real_reg_435;

assign sext_ln158_1_fu_185_p1 = value_imag_fu_167_p4;

assign sext_ln158_fu_181_p1 = value_imag_fu_167_p4;

assign sext_ln41_1_fu_239_p1 = abs_Q_V_1_reg_464;

assign sext_ln41_fu_236_p1 = abs_I_V_1_reg_452;

assign sub_ln75_1_fu_310_p2 = (16'd0 - rotation_cos_lut_q0);

assign sub_ln75_fu_297_p2 = (16'd0 - rotation_sin_lut_q0);

assign tmp_1_fu_211_p3 = in_sample_TDATA_int_regslice[32'd31];

assign tmp_fu_189_p3 = in_sample_TDATA_int_regslice[32'd15];

assign trunc_ln_fu_351_p4 = {{grp_fu_402_p2[24:9]}};

assign value_imag_fu_167_p4 = {{in_sample_TDATA_int_regslice[31:16]}};

assign value_real_fu_163_p1 = in_sample_TDATA_int_regslice[15:0];

assign xor_ln1085_fu_253_p2 = (icmp_ln1085_fu_249_p2 ^ 1'd1);

assign zext_ln587_fu_291_p1 = rotation_index_V_loc_fu_90;


reg find_kernel_block = 0;
// synthesis translate_off
`include "polar_clip_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //polar_clip

