// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="stream_out_stream_out,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvc1902-vsva2197-2MP-e-S,HLS_INPUT_CLOCK=3.200000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=1.768500,HLS_SYN_LAT=2563,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=51,HLS_SYN_LUT=65,HLS_VERSION=2024_2}" *)

module stream_out (
        ap_clk,
        ap_rst_n,
        s_TREADY,
        s_TDATA,
        s_TVALID,
        s_TKEEP,
        s_TSTRB,
        s_TLAST
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst_n;
input   s_TREADY;
output  [31:0] s_TDATA;
output   s_TVALID;
output  [3:0] s_TKEEP;
output  [3:0] s_TSTRB;
output  [0:0] s_TLAST;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_enable_reg_pp0_iter1;
wire    regslice_both_s_V_data_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_enable_reg_pp0_iter2;
wire    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln33_fu_180_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
wire   [10:0] cint16Input_address0;
wire   [15:0] cint16Input_q0;
wire   [10:0] cint16Input_address1;
wire   [15:0] cint16Input_q1;
reg    s_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [31:0] x_data_fu_208_p4;
wire   [63:0] zext_ln33_fu_144_p1;
wire   [63:0] zext_ln36_fu_171_p1;
reg   [12:0] i1_fu_78;
wire   [12:0] i_fu_138_p2;
wire    ap_loop_init;
reg   [12:0] ap_sig_allocacmp_i1_load;
reg   [31:0] x_data2_fu_82;
reg    ap_block_pp0_stage0_01001;
reg    cint16Input_ce1_local;
reg    cint16Input_ce0_local;
wire   [9:0] tmp_fu_153_p4;
wire   [10:0] or_ln_fu_163_p3;
wire   [31:0] x_data_1_fu_194_p4;
wire  signed [16:0] sext_ln36_fu_204_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_continue_int;
wire   [31:0] s_TDATA_int_regslice;
reg    s_TVALID_int_regslice;
wire    s_TREADY_int_regslice;
wire    regslice_both_s_V_data_V_U_vld_out;
wire    regslice_both_s_V_keep_V_U_apdone_blk;
wire    regslice_both_s_V_keep_V_U_ack_in_dummy;
wire    regslice_both_s_V_keep_V_U_vld_out;
wire    regslice_both_s_V_strb_V_U_apdone_blk;
wire   [3:0] s_TSTRB_int_regslice;
wire    regslice_both_s_V_strb_V_U_ack_in_dummy;
wire    regslice_both_s_V_strb_V_U_vld_out;
wire    regslice_both_s_V_last_V_U_apdone_blk;
wire    regslice_both_s_V_last_V_U_ack_in_dummy;
wire    regslice_both_s_V_last_V_U_vld_out;
reg    ap_condition_102;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 i1_fu_78 = 13'd0;
#0 x_data2_fu_82 = 32'd0;
end

stream_out_cint16Input_ROM_AUTO_1R #(
    .DataWidth( 16 ),
    .AddressRange( 2048 ),
    .AddressWidth( 11 ))
cint16Input_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .address0(cint16Input_address0),
    .ce0(cint16Input_ce0_local),
    .q0(cint16Input_q0),
    .address1(cint16Input_address1),
    .ce1(cint16Input_ce1_local),
    .q1(cint16Input_q1)
);

stream_out_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

stream_out_regslice_both #(
    .DataWidth( 32 ))
regslice_both_s_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_TDATA_int_regslice),
    .vld_in(s_TVALID_int_regslice),
    .ack_in(s_TREADY_int_regslice),
    .data_out(s_TDATA),
    .vld_out(regslice_both_s_V_data_V_U_vld_out),
    .ack_out(s_TREADY),
    .apdone_blk(regslice_both_s_V_data_V_U_apdone_blk)
);

stream_out_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(4'd15),
    .vld_in(s_TVALID_int_regslice),
    .ack_in(regslice_both_s_V_keep_V_U_ack_in_dummy),
    .data_out(s_TKEEP),
    .vld_out(regslice_both_s_V_keep_V_U_vld_out),
    .ack_out(s_TREADY),
    .apdone_blk(regslice_both_s_V_keep_V_U_apdone_blk)
);

stream_out_regslice_both #(
    .DataWidth( 4 ))
regslice_both_s_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(s_TSTRB_int_regslice),
    .vld_in(s_TVALID_int_regslice),
    .ack_in(regslice_both_s_V_strb_V_U_ack_in_dummy),
    .data_out(s_TSTRB),
    .vld_out(regslice_both_s_V_strb_V_U_vld_out),
    .ack_out(s_TREADY),
    .apdone_blk(regslice_both_s_V_strb_V_U_apdone_blk)
);

stream_out_regslice_both #(
    .DataWidth( 1 ))
regslice_both_s_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(1'd0),
    .vld_in(s_TVALID_int_regslice),
    .ack_in(regslice_both_s_V_last_V_U_ack_in_dummy),
    .data_out(s_TLAST),
    .vld_out(regslice_both_s_V_last_V_U_vld_out),
    .ack_out(s_TREADY),
    .apdone_blk(regslice_both_s_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_102)) begin
        i1_fu_78 <= i_fu_138_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        x_data2_fu_82 <= x_data_fu_208_p4;
    end
end

always @ (*) begin
    if (((icmp_ln33_fu_180_p2 == 1'd0) & (1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i1_load = 13'd0;
    end else begin
        ap_sig_allocacmp_i1_load = i1_fu_78;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cint16Input_ce0_local = 1'b1;
    end else begin
        cint16Input_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cint16Input_ce1_local = 1'b1;
    end else begin
        cint16Input_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        s_TDATA_blk_n = s_TREADY_int_regslice;
    end else begin
        s_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        s_TVALID_int_regslice = 1'b1;
    end else begin
        s_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_s_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_s_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (regslice_both_s_V_data_V_U_apdone_blk == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_pp0_stage0_iter1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (s_TREADY_int_regslice == 1'b0);
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_s_V_data_V_U_apdone_blk == 1'b1) | (s_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_condition_102 = ((1'b1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready_pp0_iter2_reg = 1'b0;

assign cint16Input_address0 = zext_ln36_fu_171_p1;

assign cint16Input_address1 = zext_ln33_fu_144_p1;

assign i_fu_138_p2 = (ap_sig_allocacmp_i1_load + 13'd2);

assign icmp_ln33_fu_180_p2 = ((i_fu_138_p2 < 13'd5120) ? 1'b1 : 1'b0);

assign or_ln_fu_163_p3 = {{tmp_fu_153_p4}, {1'd1}};

assign s_TDATA_int_regslice = {{sext_ln36_fu_204_p1}, {x_data_1_fu_194_p4[15:0]}};

assign s_TSTRB_int_regslice = 'bx;

assign s_TVALID = regslice_both_s_V_data_V_U_vld_out;

assign sext_ln36_fu_204_p1 = $signed(cint16Input_q0);

assign tmp_fu_153_p4 = {{ap_sig_allocacmp_i1_load[10:1]}};

assign x_data_1_fu_194_p4 = {{x_data2_fu_82[31:16]}, {cint16Input_q1}};

assign x_data_fu_208_p4 = {{sext_ln36_fu_204_p1}, {x_data_1_fu_194_p4[15:0]}};

assign zext_ln33_fu_144_p1 = ap_sig_allocacmp_i1_load;

assign zext_ln36_fu_171_p1 = or_ln_fu_163_p3;


reg find_kernel_block = 0;
// synthesis translate_off
`include "stream_out_hls_deadlock_kernel_monitor_top.vh"
// synthesis translate_on

endmodule //stream_out

