// 
// Copyright (C) 2023, Advanced Micro Devices, Inc. All rights reserved.
// SPDX-License-Identifier: MIT
// 

#ifndef __DDC_INCLUDE_H__
#define __DDC_INCLUDE_H__

#define CEIL_TO_8(x) (((x+7)/8)*8)


#define DDC_NCH_NR 1
#define DDC_NCH_LTE 5
#define DDC_HEAD_LEN 8
#define DDC_NR_SAMPLES_PERCH 256 
#define DDC_NR_SAMPLES_PERCH2D 128
#define DDC_NR_SAMPLES_PERCH4D 64
#define DDC_LTE_SAMPLES_PERCH 256 
#define DDC_LTE_SAMPLES_PERCH2D 128
#define DDC_LTE_SAMPLES_PERCH4D 64

#define DDC_TX_INPUT_SAMPLES 640

#define DDC_INPUT_SAMPLES (DDC_TX_INPUT_SAMPLES+DDC_HEAD_LEN)
#define DDC_OUTPUT_SAMPLES 320
#define DDC_IN_BLOCK_SIZE      (4*DDC_INPUT_SAMPLES)
#define DDC_OUT_BLOCK_SIZE     (4*DDC_OUTPUT_SAMPLES)
#define DEMIXER_CARR1P 31
#define DEMIXER_CARR4P 127
#define HBFD_INBSIZE 32
#define HBFD_OUTBSIZE 32
#define DDC_NR_INBSIZE 16
#define DDC_NR_OUTBSIZE 32
#define DDC_LTE_INBSIZE 16
#define DDC_LTE_OUTBSIZE 16


#define HBF47D_INPUT_SAMPLES 512
#define HBF47D_INPUT_MARGIN 0
#define HBF47D_OUTPUT_SAMPLES 256
#define HBF47D_IN_BLOCK_SIZE ((HBF47D_INPUT_SAMPLES+DDC_HEAD_LEN)*4)
#define HBF47D_OUTPUT_SIZE ((HBF47D_OUTPUT_SAMPLES+DDC_HEAD_LEN)*4)
#define HBF47D_IN_OVERLAP_SIZE (HBF47D_INPUT_MARGIN*4)


#define HBFD_INPUT_SAMPLES 1280
#define HBFD_INPUT_MARGIN 0
#define HBFD_OUTPUT_SAMPLES 640
#define HBFD_IN_BLOCK_SIZE ((HBFD_INPUT_SAMPLES+DDC_HEAD_LEN)*4)
#define HBFD_OUTPUT_SIZE ((HBFD_OUTPUT_SAMPLES+DDC_HEAD_LEN)*4)
#define HBFD_IN_OVERLAP_SIZE (HBFD_INPUT_MARGIN*4)


#endif
