%
% Copyright (C) 2026, Advanced Micro Devices, Inc. All rights reserved.
% SPDX-License-Identifier: MIT
%
% Author: Richard Buz
%

function chnlzr_in = dmux_ssr_input(wb_smp)
% Demultiplexes the wideband input signal into 7 SSR streams for the
% channelizer filterbank input (P/Q = 8/7). Scales and converts to int16.

N = length(wb_smp);

chnlzr_in = int16(2^15 * [ ...
    wb_smp(reshape([(14:14:N)' (7:14:N)']',N/7,1)) ...
    wb_smp(reshape([(13:14:N)' (6:14:N)']',N/7,1)) ...
    wb_smp(reshape([(12:14:N)' (5:14:N)']',N/7,1)) ...
    wb_smp(reshape([(11:14:N)' (4:14:N)']',N/7,1)) ...
    wb_smp(reshape([(10:14:N)' (3:14:N)']',N/7,1)) ...
    wb_smp(reshape([(9:14:N)' (2:14:N)']',N/7,1)) ...
    wb_smp(reshape([(8:14:N)' (1:14:N)']',N/7,1)) ...
    ]);

end
